In [5]:
import pandas as pd
from os import scandir, rename
from os.path import join
from tqdm.notebook import tqdm
dataset = "civilcomments"

In [8]:
#methods = ["jtt_60_100_625", "jtt_60_100_75","jtt_60_100_875","jtt_60_100_95", "gdro_1_625",
#           "gdro_1_75", "gdro_1_875", "gdro_1_95"]

methods = ["erm_0.9", "rw_erm_0.9", "gdro_0.9", "dfr_0.9", "erm_rw_0.9", "erm_gdro_0.9"]
for split in ['val','test']: # Find all final epoch results CSVs
    exps = []
    for f in scandir(dataset):
        if f.path.split("/")[-1] in methods:
            for f1 in scandir(f.path):
            #if "jto" in f1.path:
                exps.append(join(f1.path,f"{split}.csv"))
    results  = pd.DataFrame()
    # Create 
    print(exps)
    for f in tqdm(exps):
        csv = pd.read_csv(f)
        data = f.split("/")[1]

        if dataset == "CelebA":
            corr = 0.9
            method = data
        else:
            method = "_".join(data.split("_")[:-1])
            corr = data.split("_")[-1]
        seed = f.split("/")[2].split("_")[-1]
        #print(f,method,corr)
        csv['method'] = method
        csv['corr'] = corr
        csv['seed'] = seed

        results = pd.concat([results, csv])
        #print(results.columns)
    results.to_csv(f'{dataset}_FINAL_{split}.csv', index=False)

['civilcomments/erm_gdro_0.9/model_outputs_111/val.csv', 'civilcomments/erm_gdro_0.9/model_outputs_333/val.csv', 'civilcomments/erm_gdro_0.9/model_outputs_222/val.csv', 'civilcomments/gdro_0.9/model_outputs_111/val.csv', 'civilcomments/gdro_0.9/model_outputs_333/val.csv', 'civilcomments/gdro_0.9/model_outputs_222/val.csv', 'civilcomments/rw_erm_0.9/model_outputs_111/val.csv', 'civilcomments/rw_erm_0.9/model_outputs_333/val.csv', 'civilcomments/rw_erm_0.9/model_outputs_222/val.csv', 'civilcomments/erm_0.9/model_outputs_111/val.csv', 'civilcomments/erm_0.9/model_outputs_333/val.csv', 'civilcomments/erm_0.9/model_outputs_222/val.csv', 'civilcomments/erm_rw_0.9/model_outputs_111/val.csv', 'civilcomments/erm_rw_0.9/model_outputs_333/val.csv', 'civilcomments/erm_rw_0.9/model_outputs_222/val.csv', 'civilcomments/dfr_0.9/model_outputs_111/val.csv', 'civilcomments/dfr_0.9/model_outputs_333/val.csv', 'civilcomments/dfr_0.9/model_outputs_222/val.csv']

  0%|          | 0/18 [00:00<?, ?it/s]

['civilcomments/erm_gdro_0.9/model_outputs_111/test.csv', 'civilcomments/erm_gdro_0.9/model_outputs_333/test.csv', 'civilcomments/erm_gdro_0.9/model_outputs_222/test.csv', 'civilcomments/gdro_0.9/model_outputs_111/test.csv', 'civilcomments/gdro_0.9/model_outputs_333/test.csv', 'civilcomments/gdro_0.9/model_outputs_222/test.csv', 'civilcomments/rw_erm_0.9/model_outputs_111/test.csv', 'civilcomments/rw_erm_0.9/model_outputs_333/test.csv', 'civilcomments/rw_erm_0.9/model_outputs_222/test.csv', 'civilcomments/erm_0.9/model_outputs_111/test.csv', 'civilcomments/erm_0.9/model_outputs_333/test.csv', 'civilcomments/erm_0.9/model_outputs_222/test.csv', 'civilcomments/erm_rw_0.9/model_outputs_111/test.csv', 'civilcomments/erm_rw_0.9/model_outputs_333/test.csv', 'civilcomments/erm_rw_0.9/model_outputs_222/test.csv', 'civilcomments/dfr_0.9/model_outputs_111/test.csv', 'civilcomments/dfr_0.9/model_outputs_333/test.csv', 'civilcomments/dfr_0.9/model_outputs_222/test.csv']

  0%|          | 0/18 [00:00<?, ?it/s]

In [15]:
exps

['MultiNLI/gdro_0.9/model_outputs_111/test.csv',
 'MultiNLI/rw_0.9/model_outputs_111/test.csv',
 'MultiNLI/erm_0.9/model_outputs_111/test.csv']

In [19]:

results  = pd.DataFrame()
for f in exps:
        csv = pd.read_csv(f)
        data = f.split("/")[1]

        if dataset == "CelebA":
            corr = 0.9
            method = data
        else:
            method = "_".join(data.split("_")[:-1])
            corr = data.split("_")[-1]
        seed = f.split("/")[2].split("_")[-1]
        #print(f,method,corr)
        csv['method'] = method
        csv['corr'] = corr
        csv['seed'] = seed
        results = pd.concat([results, csv])

In [20]:
results

,epoch,batch,avg_loss_group:0,exp_avg_loss_group:0,avg_acc_group:0,processed_data_count_group:0,update_data_count_group:0,update_batch_count_group:0,avg_loss_group:1,exp_avg_loss_group:1,...,update_data_count_group:5,update_batch_count_group:5,avg_actual_loss,avg_per_sample_loss,avg_acc,model_norm_sq,reg_loss,method,corr,seed
0,0,3865,0.712963,0.682966,0.742983,34597.0,34597.0,3866.0,0.412310,0.315113,...,1148.0,1019.0,0.661574,0.549208,0.791815,204366.546875,0.0,gdro,0.9,111
1,1,3865,0.615369,0.602681,0.792093,34597.0,34597.0,3866.0,0.502327,0.319703,...,1148.0,1019.0,0.570663,0.537683,0.806656,204486.734375,0.0,gdro,0.9,111
2,2,3865,0.723341,0.742204,0.784027,34597.0,34597.0,3866.0,0.400760,0.303519,...,1148.0,1019.0,0.672529,0.563314,0.814868,204554.531250,0.0,gdro,0.9,111
3,3,3865,0.652405,0.675864,0.813193,34597.0,34597.0,3866.0,0.299306,0.253892,...,1148.0,1019.0,0.602066,0.573076,0.819282,204583.437500,0.0,gdro,0.9,111
4,4,3865,0.680482,0.711153,0.807064,34597.0,34597.0,3866.0,0.292308,0.255267,...,1148.0,1019.0,0.628952,0.592105,0.819160,204589.609375,0.0,gdro,0.9,111
0,0,3865,0.608590,0.547927,0.771830,34597.0,34597.0,3866.0,0.237093,0.146760,...,1148.0,1019.0,0.561407,0.561408,0.789964,204397.703125,0.0,rw,0.9,111
1,1,3865,0.572025,0.574669,0.802988,34597.0,34597.0,3866.0,0.230150,0.182003,...,1148.0,1019.0,0.544672,0.544671,0.810834,204524.671875,0.0,rw,0.9,111
2,2,3865,0.582990,0.643240,0.812354,34597.0,34597.0,3866.0,0.250981,0.199368,...,1148.0,1019.0,0.560621,0.560621,0.816072,204594.453125,0.0,rw,0.9,111
3,3,3865,0.613433,0.660108,0.824290,34597.0,34597.0,3866.0,0.326064,0.278528,...,1148.0,1019.0,0.614314,0.614312,0.816743,204623.937500,0.0,rw,0.9,111
4,4,3865,0.643751,0.680113,0.817413,34597.0,34597.0,3866.0,0.295092,0.237742,...,1148.0,1019.0,0.624439,0.624439,0.819669,204629.875000,0.0,rw,0.9,111
0,0,3865,0.594576,0.622462,0.766916,34597.0,34597.0,3866.0,0.186483,0.145034,...,1148.0,1019.0,0.468455,0.468454,0.816517,204370.593750,0.0,erm,0.9,111
1,1,3865,0.512167,0.521472,0.822702,34597.0,34597.0,3866.0,0.120019,0.074730,...,1148.0,1019.0,0.474313,0.474313,0.824091,204512.375000,0.0,erm,0.9,111
2,2,3865,0.562595,0.582427,0.817528,34597.0,34597.0,3866.0,0.127210,0.079174,...,1148.0,1019.0,0.532276,0.532276,0.822677,204599.734375,0.0,erm,0.9,111
3,3,3865,0.737400,0.758958,0.818830,34597.0,34597.0,3866.0,0.153599,0.149613,...,1148.0,1019.0,0.666591,0.666592,0.823921,204638.906250,0.0,erm,0.9,111
4,4,3865,0.870861,0.868325,0.819435,34597.0,34597.0,3866.0,0.181507,0.180171,...,1148.0,1019.0,0.797518,0.797517,0.823323,204647.171875,0.0,erm,0.9,111

In [21]:
from glob import glob
from os import remove
files_to_delete = []
exps = []
for f in scandir(dataset):
        for f1 in scandir(f.path):
                print(f1.path)
                exps.extend(glob(f"{f1.path}/output_*_epoch_*.csv"))

MultiNLI/gdro_0.9/model_outputs_111
MultiNLI/erm_0.9_old/model_outputs_111
MultiNLI/erm_0.9_old/model_outputs_333
MultiNLI/erm_0.9_old/model_outputs_222
MultiNLI/rw_0.9_old/model_outputs_111
MultiNLI/rw_0.9_old/model_outputs_333
MultiNLI/rw_0.9_old/model_outputs_222
MultiNLI/gdro_0.9_old/model_outputs_111
MultiNLI/gdro_0.9_old/model_outputs_333
MultiNLI/gdro_0.9_old/model_outputs_222
MultiNLI/rw_0.9/model_outputs_111
MultiNLI/erm_0.9/model_outputs_111

CUB/erm_dfr_gdro_2_50/model_outputs_111
CUB/erm_dfr_gdro_2_50/model_outputs_333
CUB/erm_dfr_2_625/model_outputs_222
CUB/erm_dfr_2_625/model_outputs_111
CUB/erm_dfr_2_625/model_outputs_333
CUB/erm_dfr_gdro_2_625/model_outputs_111
CUB/erm_dfr_gdro_2_625/model_outputs_222
CUB/erm_dfr_gdro_2_625/model_outputs_333
CUB/erm_dfr_2_75/model_outputs_222
CUB/erm_dfr_2_75/model_outputs_333
CUB/erm_dfr_2_75/model_outputs_111
CUB/erm_dfr_gdro_2_75/model_outputs_111
CUB/erm_dfr_gdro_2_75/model_outputs_222
CUB/erm_dfr_gdro_2_75/model_outputs_333
CUB/erm_dfr_2_875/model_outputs_222
CUB/erm_dfr_2_875/model_outputs_333
CUB/erm_dfr_2_875/model_outputs_111
CUB/erm_dfr_2_95/model_outputs_333
CUB/erm_dfr_2_95/model_outputs_111
CUB/erm_dfr_2_95/model_outputs_222
CUB/erm_rw_0.1_95/model_outputs_111
CUB/erm_rw_0.1_95/model_outputs_333
CUB/erm_rw_0.1_95/model_outputs_222
CUB/erm_rw_0.25_95/model_outputs_222
CUB/erm_rw_0.25_95/model_outputs_111
CUB/erm_rw_0.25_95/model_outputs_333
CUB/erm_dfr_gdro_2_875/model_outputs_222
CUB/erm_dfr_gdro_2_875/model_outputs_111
CUB/erm_dfr_gdro_2_875/model_outputs_333
CUB/erm_dfr_gdro_2_95/model_outputs_222
CUB/erm_dfr_gdro_2_95/model_outputs_111
CUB/erm_dfr_gdro_2_95/model_outputs_333
CUB/erm_dfr_new_625/model_outputs_333
CUB/erm_dfr_new_625/model_outputs_222
CUB/erm_dfr_new_625/model_outputs_111
CUB/erm_dfr_gdro_new_625/model_outputs_111
CUB/erm_dfr_gdro_new_625/model_outputs_222
CUB/erm_dfr_gdro_new_625/model_outputs_333
CUB/erm_dfr_new_75/model_outputs_111
CUB/erm_dfr_new_75/model_outputs_333
CUB/erm_dfr_new_75/model_outputs_222
CUB/erm_rw_0.5_95/model_outputs_111
CUB/erm_rw_0.5_95/model_outputs_222
CUB/erm_rw_0.5_95/model_outputs_333
CUB/erm_rw_0.75_95/model_outputs_333
CUB/erm_rw_0.75_95/model_outputs_222
CUB/erm_rw_0.75_95/model_outputs_111
CUB/erm_rw_0.9_95/model_outputs_111
CUB/erm_rw_0.9_95/model_outputs_222
CUB/erm_rw_0.9_95/model_outputs_333
CUB/erm_gdro_0.1_95/model_outputs_111
CUB/erm_gdro_0.1_95/model_outputs_222
CUB/erm_gdro_0.1_95/model_outputs_333
CUB/erm_gdro_0.25_95/model_outputs_333
CUB/erm_gdro_0.25_95/model_outputs_222
CUB/erm_gdro_0.25_95/model_outputs_111
CUB/erm_gdro_0.5_95/model_outputs_111
CUB/erm_gdro_0.5_95/model_outputs_333
CUB/erm_gdro_0.5_95/model_outputs_222
CUB/erm_gdro_0.75_95/model_outputs_333
CUB/erm_gdro_0.75_95/model_outputs_222
CUB/erm_gdro_0.75_95/model_outputs_111
CUB/erm_gdro_0.9_95/model_outputs_111
CUB/erm_gdro_0.9_95/model_outputs_222
CUB/erm_gdro_0.9_95/model_outputs_333
CUB/erm_dfr_gdro_new_75/model_outputs_222
CUB/erm_dfr_gdro_new_75/model_outputs_111
CUB/erm_dfr_gdro_new_75/model_outputs_333
CUB/erm_dfr_new_875/model_outputs_333
CUB/erm_dfr_new_875/model_outputs_111
CUB/erm_dfr_new_875/model_outputs_222
CUB/erm_dfr_gdro_new_875/model_outputs_111
CUB/erm_dfr_gdro_new_875/model_outputs_333
CUB/erm_dfr_gdro_new_875/model_outputs_222
CUB/erm_dfr_new_95/model_outputs_111
CUB/erm_dfr_new_95/model_outputs_333
CUB/erm_dfr_new_95/model_outputs_222
CUB/erm_dfr_gdro_new_95/model_outputs_111
CUB/erm_dfr_gdro_new_95/model_outputs_222
CUB/erm_dfr_rw_new_625/model_outputs_111
CUB/erm_dfr_rw_new_625/model_outputs_222
CUB/erm_dfr_rw_new_625/model_outputs_333
CUB/erm_dfr_rw_new_75/model_outputs_222
CUB/erm_dfr_rw_new_75/model_outputs_111
CUB/erm_dfr_rw_new_75/model_outputs_333

In [29]:
for exp in exps:
    remove(exp)

In [ ]:
exps

In [ ]:
#Remove .pth for files that are not best model
from glob import glob
from os import remove
files_to_delete = []
exps = []
for f in scandir(dataset):
        for f1 in scandir(f.path):
                print(f1.path)
                exps.extend(glob(f"{f1.path}/*_model.pth"))

In [6]:
exps

['MultiNLI/erm_0.9/model_outputs_111/test.csv',
 'MultiNLI/erm_0.9/model_outputs_222/test.csv',
 'MultiNLI/erm_0.9/model_outputs_333/test.csv',
 'MultiNLI/rw_0.9/model_outputs_111/test.csv',
 'MultiNLI/rw_0.9/model_outputs_222/test.csv',
 'MultiNLI/rw_0.9/model_outputs_333/test.csv',
 'MultiNLI/gdro_0.9/model_outputs_333/test.csv',
 'MultiNLI/gdro_0.9/model_outputs_222/test.csv',
 'MultiNLI/gdro_0.9/model_outputs_111/test.csv']

In [46]:
models_to_delete = [exp for exp in exps if "best_model.pth" not in exp and "/0_model.pth" not in exp]

In [ ]:
models_to_delete

In [48]:
for m in models_to_delete:
    remove(m)

## Create Table

In [3]:
a = {50: 0.0, 625: 0.25, 75:0.5, 875: 0.75, 95:0.9}
def format_perc(perc):
    return '{:.2f}\%'.format(perc)
def format_float(perc):
    return '{:.2f}'.format(perc)
splits = ['val','test']

'''
- 'means' = overall results per method, get max value from each seed, 
then average results by seed. For results table.
- 'all' = raw results from csvs
- 'seed' = best result for seed
- 'epoch' = results averaged by seed at the epoch level. For plotting.
'''
def create_results_table(dataset, split, metric="worst_acc"):
    results = pd.read_csv(f'{dataset}_FINAL_{split}.csv')
    if dataset != "MultiNLI":
        results['worst_acc'] = results[['avg_acc_group:0','avg_acc_group:1','avg_acc_group:2','avg_acc_group:3']].min(axis=1)
    else:
        results['worst_acc'] = results[['avg_acc_group:0','avg_acc_group:1','avg_acc_group:2','avg_acc_group:3','avg_acc_group:4','avg_acc_group:5']].min(axis=1)
    epoch_df = results.groupby(['method','corr',"epoch"]).agg(
        {'worst_acc': 'mean','avg_acc': 'mean'}
    ).reset_index()
    grouped_df = results.groupby(['method','corr','seed']).agg(
        {'avg_acc': 'max', 'worst_acc': 'max'}
    ).reset_index()
    means_df = grouped_df.groupby(['method','corr']).agg(
        {'avg_acc':'mean','worst_acc':'mean'}
    ).reset_index()
    for m in ['worst_acc','avg_acc']:
        means_df[m] = 100*means_df[m]
        means_df[f'{m}_std'] = 100*grouped_df.groupby(['method','corr'])[m].std().reset_index()[m]
        means_df['count'] = grouped_df.groupby(['method','corr'])[m].count().reset_index()[m]
        means_df[m] = means_df[m].apply(format_perc)
        means_df[f'{m}_std'] = means_df[f'{m}_std'].apply(format_float)
        means_df[f'final_{m}'] = (means_df[m]).astype(str) + " $\pm$ " + means_df[f'{m}_std'].astype(str) + " (" + means_df['count'].astype(str) + ")"
    return {'means': means_df, 'seed': grouped_df, 'all': results, 'epoch': epoch_df}

def create_final_table(df, metric="avg_acc"):
    final_table = df.pivot(index='method',
                           columns='corr',
                           values=([f"final_{metric}"])).reset_index()

    return final_table

In [4]:
dataset = "MultiNLI"
results = dict()
splits = ['val','test']
for s in splits:
    results[s] =create_results_table(dataset, s)
    display(create_final_table(results[s]['means'],"worst_acc"))
    display(create_final_table(results[s]['means'],"avg_acc"))

        method         final_worst_acc
corr                               0.9
0          dfr  87.44\% $\pm$ 4.81 (3)
1          erm  67.96\% $\pm$ 1.26 (3)
2     erm_gdro  88.39\% $\pm$ 4.16 (3)
3       erm_rw  87.52\% $\pm$ 4.75 (3)
4         gdro  76.58\% $\pm$ 0.57 (3)

        method           final_avg_acc
corr                               0.9
0          dfr  91.87\% $\pm$ 1.91 (3)
1          erm  82.44\% $\pm$ 0.13 (3)
2     erm_gdro  91.85\% $\pm$ 1.91 (3)
3       erm_rw  91.85\% $\pm$ 1.92 (3)
4         gdro  82.02\% $\pm$ 0.08 (3)

        method         final_worst_acc
corr                               0.9
0          dfr  69.37\% $\pm$ 1.10 (3)
1          erm  69.45\% $\pm$ 2.18 (3)
2     erm_gdro  73.46\% $\pm$ 2.35 (3)
3       erm_rw  69.34\% $\pm$ 0.78 (3)
4         gdro  76.67\% $\pm$ 0.62 (3)

        method           final_avg_acc
corr                               0.9
0          dfr  82.58\% $\pm$ 0.25 (3)
1          erm  82.55\% $\pm$ 0.14 (3)
2     erm_gdro  82.56\% $\pm$ 0.22 (3)
3       erm_rw  82.58\% $\pm$ 0.24 (3)
4         gdro  82.02\% $\pm$ 0.09 (3)

In [9]:
dataset = "civilcomments"
results = dict()
splits = ['val','test']
for s in splits:
    results[s] =create_results_table(dataset, s)
    display(create_final_table(results[s]['means'],"worst_acc"))
    display(create_final_table(results[s]['means'],"avg_acc"))

        method         final_worst_acc
corr                               0.9
0          dfr  84.74\% $\pm$ 1.32 (3)
1          erm  65.28\% $\pm$ 2.10 (3)
2     erm_gdro  84.15\% $\pm$ 1.17 (3)
3       erm_rw  84.09\% $\pm$ 0.87 (3)
4         gdro  79.15\% $\pm$ 2.18 (3)
5       rw_erm  80.19\% $\pm$ 2.13 (3)

        method           final_avg_acc
corr                               0.9
0          dfr  92.86\% $\pm$ 2.15 (3)
1          erm  93.00\% $\pm$ 0.07 (3)
2     erm_gdro  92.28\% $\pm$ 2.50 (3)
3       erm_rw  92.92\% $\pm$ 2.14 (3)
4         gdro  91.11\% $\pm$ 0.35 (3)
5       rw_erm  91.44\% $\pm$ 0.06 (3)

        method         final_worst_acc
corr                               0.9
0          dfr  80.79\% $\pm$ 0.73 (3)
1          erm  66.14\% $\pm$ 2.42 (3)
2     erm_gdro  77.86\% $\pm$ 5.09 (3)
3       erm_rw  80.34\% $\pm$ 0.98 (3)
4         gdro  79.89\% $\pm$ 3.34 (3)
5       rw_erm  80.00\% $\pm$ 2.35 (3)

        method           final_avg_acc
corr                               0.9
0          dfr  90.35\% $\pm$ 1.63 (3)
1          erm  92.96\% $\pm$ 0.11 (3)
2     erm_gdro  89.86\% $\pm$ 1.99 (3)
3       erm_rw  90.42\% $\pm$ 1.72 (3)
4         gdro  91.04\% $\pm$ 0.38 (3)
5       rw_erm  91.27\% $\pm$ 0.01 (3)

In [6]:
dataset = "CUB"
results = dict()
splits = ['val','test']
for s in splits:
    results[s] =create_results_table(dataset, s)
    display(create_final_table(results[s]['means'],"worst_acc"))
    display(create_final_table(results[s]['means'],"avg_acc"))

                     method         final_worst_acc                          \
corr                                             50                      75
0                       erm  87.31\% $\pm$ 1.29 (3)  88.81\% $\pm$ 1.03 (3)
1                   erm_dfr                     NaN  92.79\% $\pm$ 0.86 (3)
2                 erm_dfr_2  83.08\% $\pm$ 0.43 (3)  83.22\% $\pm$ 0.67 (3)
3              erm_dfr_gdro                     NaN  94.53\% $\pm$ 0.86 (3)
4            erm_dfr_gdro_2  82.09\% $\pm$ 1.29 (3)  80.98\% $\pm$ 0.77 (3)
5          erm_dfr_gdro_new                     NaN  95.27\% $\pm$ 0.43 (3)
6      erm_dfr_gdro_new_0.1                     NaN                     NaN
7     erm_dfr_gdro_new_0.25                     NaN                     NaN
8      erm_dfr_gdro_new_0.5                     NaN                     NaN
9     erm_dfr_gdro_new_0.75                     NaN                     NaN
10     erm_dfr_gdro_new_0.9                     NaN                     NaN
11              erm_dfr_new                     NaN  94.83\% $\pm$ 0.04 (3)
12           erm_dfr_rw_new                     NaN  95.11\% $\pm$ 0.36 (3)
13       erm_dfr_rw_new_0.1                     NaN                     NaN
14      erm_dfr_rw_new_0.25                     NaN                     NaN
15       erm_dfr_rw_new_0.5                     NaN                     NaN
16      erm_dfr_rw_new_0.75                     NaN                     NaN
17       erm_dfr_rw_new_0.9                     NaN                     NaN
18                 erm_gdro  82.59\% $\pm$ 0.43 (3)  85.01\% $\pm$ 0.77 (3)
19             erm_gdro_0.1                     NaN                     NaN
20            erm_gdro_0.25                     NaN                     NaN
21             erm_gdro_0.5                     NaN                     NaN
22            erm_gdro_0.75                     NaN                     NaN
23             erm_gdro_0.9                     NaN                     NaN
24            erm_gdro_frz0  90.05\% $\pm$ 1.55 (3)  90.81\% $\pm$ 0.35 (3)
25            erm_gdro_frz1  90.30\% $\pm$ 1.29 (3)  90.81\% $\pm$ 0.35 (3)
26            erm_gdro_frz2  89.55\% $\pm$ 1.97 (3)  90.78\% $\pm$ 0.30 (3)
27            erm_gdro_frz3  89.55\% $\pm$ 2.24 (3)  91.05\% $\pm$ 0.39 (3)
28            erm_gdro_frz4  91.29\% $\pm$ 0.43 (3)  91.44\% $\pm$ 0.39 (3)
29        erm_gdro_frz_rst1  90.55\% $\pm$ 0.43 (3)  89.86\% $\pm$ 0.00 (3)
30        erm_gdro_frz_rst2  89.80\% $\pm$ 0.43 (3)  89.64\% $\pm$ 0.72 (3)
31        erm_gdro_frz_rst3  89.30\% $\pm$ 0.86 (3)  90.54\% $\pm$ 0.00 (3)
32        erm_gdro_frz_rst4  92.04\% $\pm$ 0.43 (3)  91.67\% $\pm$ 0.39 (3)
33                   erm_rw  81.09\% $\pm$ 0.43 (3)  82.33\% $\pm$ 0.77 (3)
34               erm_rw_0.1                     NaN                     NaN
35              erm_rw_0.25                     NaN                     NaN
36               erm_rw_0.5                     NaN                     NaN
37              erm_rw_0.75                     NaN                     NaN
38               erm_rw_0.9                     NaN                     NaN
39                     gdro  88.81\% $\pm$ 1.29 (3)  88.76\% $\pm$ 0.43 (3)
40                   gdro_1  90.80\% $\pm$ 0.43 (3)  89.86\% $\pm$ 0.00 (3)
41                 gdro_dfr                     NaN  90.28\% $\pm$ 2.68 (3)
42                 gdro_erm  85.32\% $\pm$ 1.14 (3)  88.32\% $\pm$ 0.76 (3)
43            gdro_erm_frz1  88.31\% $\pm$ 0.86 (3)  86.58\% $\pm$ 0.67 (3)
44            gdro_erm_frz2  88.31\% $\pm$ 0.86 (3)  86.80\% $\pm$ 0.77 (3)
45            gdro_erm_frz3  88.31\% $\pm$ 0.86 (3)  87.02\% $\pm$ 0.39 (3)
46            gdro_erm_frz4  87.31\% $\pm$ 0.75 (3)  89.04\% $\pm$ 0.39 (3)
47                gdro_gdro  90.30\% $\pm$ 1.29 (3)  89.21\% $\pm$ 0.04 (3)
48              gdro_gdro_1  91.04\% $\pm$ 0.00 (3)  90.09\% $\pm$ 0.39 (3)
49            gdro_gdro_dfr                     NaN  93.22\% $\pm$ 1.96 (3)
50                  gdro_rw   91.79\% $\pm$ nan (1)   90.47\% $\pm$ nan (1)
51                   rw_erm  88.81\% $\pm$ 1.29 (3)  88.79\% $\pm$ 0.41 (3)


corr                      95                     625                     875
0     69.17\% $\pm$ 0.75 (3)  85.99\% $\pm$ 0.49 (3)  83.33\% $\pm$ 0.79 (3)
1     82.16\% $\pm$ 2.02 (3)  92.29\% $\pm$ 1.14 (3)  87.56\% $\pm$ 3.45 (3)
2     68.00\% $\pm$ 5.59 (3)  83.47\% $\pm$ 0.49 (3)  79.10\% $\pm$ 3.58 (3)
3     87.06\% $\pm$ 1.72 (3)  95.15\% $\pm$ 0.53 (2)  90.80\% $\pm$ 2.15 (3)
4     66.15\% $\pm$ 6.04 (3)  82.63\% $\pm$ 0.49 (3)  76.98\% $\pm$ 4.20 (3)
5     89.80\% $\pm$ 1.14 (3)  95.65\% $\pm$ 0.44 (3)  94.28\% $\pm$ 0.86 (3)
6     83.34\% $\pm$ 5.66 (3)                     NaN                     NaN
7     87.54\% $\pm$ 2.78 (3)                     NaN                     NaN
8     89.06\% $\pm$ 1.87 (3)                     NaN                     NaN
9     90.66\% $\pm$ 1.62 (3)                     NaN                     NaN
10    91.38\% $\pm$ 0.71 (3)                     NaN                     NaN
11    89.30\% $\pm$ 1.14 (3)  95.27\% $\pm$ 0.86 (3)  93.78\% $\pm$ 0.43 (3)
12    89.60\% $\pm$ 1.56 (3)  95.52\% $\pm$ 0.75 (3)  94.23\% $\pm$ 0.82 (3)
13    83.49\% $\pm$ 5.86 (3)                     NaN                     NaN
14    87.32\% $\pm$ 2.58 (3)                     NaN                     NaN
15    89.05\% $\pm$ 1.88 (3)                     NaN                     NaN
16    90.49\% $\pm$ 1.48 (3)                     NaN                     NaN
17    90.85\% $\pm$ 0.48 (3)                     NaN                     NaN
18    69.67\% $\pm$ 3.55 (3)  83.75\% $\pm$ 0.49 (3)  81.75\% $\pm$ 0.00 (3)
19    46.62\% $\pm$ 1.50 (3)                     NaN                     NaN
20    57.64\% $\pm$ 2.42 (3)                     NaN                     NaN
21    65.57\% $\pm$ 2.17 (3)                     NaN                     NaN
22    68.92\% $\pm$ 3.04 (3)                     NaN                     NaN
23    68.17\% $\pm$ 0.43 (3)                     NaN                     NaN
24    82.11\% $\pm$ 0.14 (3)  87.11\% $\pm$ 0.49 (3)  90.48\% $\pm$ 1.59 (3)
25    81.90\% $\pm$ 0.12 (3)  87.11\% $\pm$ 0.49 (3)  90.48\% $\pm$ 1.59 (3)
26    82.50\% $\pm$ 0.47 (3)  87.39\% $\pm$ 0.84 (3)  90.64\% $\pm$ 1.54 (3)
27    81.97\% $\pm$ 0.57 (3)  87.58\% $\pm$ 0.58 (3)  90.74\% $\pm$ 0.92 (3)
28    84.29\% $\pm$ 1.41 (3)  89.83\% $\pm$ 0.00 (3)  90.49\% $\pm$ 0.02 (3)
29    85.55\% $\pm$ 0.12 (3)  86.80\% $\pm$ 0.94 (3)  91.01\% $\pm$ 0.46 (3)
30    84.65\% $\pm$ 0.40 (3)  86.55\% $\pm$ 0.84 (3)  90.74\% $\pm$ 0.46 (3)
31    83.61\% $\pm$ 0.26 (3)  87.39\% $\pm$ 0.84 (3)  91.30\% $\pm$ 0.05 (3)
32    83.21\% $\pm$ 1.74 (3)  90.11\% $\pm$ 0.49 (3)  90.21\% $\pm$ 0.46 (3)
33    61.65\% $\pm$ 0.75 (3)  83.19\% $\pm$ 0.00 (3)  77.78\% $\pm$ 0.79 (3)
34    42.61\% $\pm$ 0.43 (3)                     NaN                     NaN
35    50.13\% $\pm$ 0.87 (3)                     NaN                     NaN
36    57.39\% $\pm$ 5.12 (3)                     NaN                     NaN
37    62.16\% $\pm$ 1.15 (3)                     NaN                     NaN
38    62.16\% $\pm$ 2.30 (3)                     NaN                     NaN
39    82.21\% $\pm$ 0.43 (3)  86.55\% $\pm$ 0.84 (3)  89.15\% $\pm$ 1.21 (3)
40    85.98\% $\pm$ 0.44 (3)  86.53\% $\pm$ 0.84 (3)  90.48\% $\pm$ 0.00 (3)
41    74.63\% $\pm$ 1.29 (3)  89.38\% $\pm$ 3.38 (3)  89.35\% $\pm$ 0.48 (3)
42    62.66\% $\pm$ 3.04 (3)  84.03\% $\pm$ 1.46 (3)  88.94\% $\pm$ 0.80 (3)
43    69.42\% $\pm$ 1.89 (3)  86.27\% $\pm$ 2.57 (3)  89.15\% $\pm$ 0.46 (3)
44    69.67\% $\pm$ 1.15 (3)  86.27\% $\pm$ 2.57 (3)  89.15\% $\pm$ 0.46 (3)
45    69.42\% $\pm$ 1.15 (3)  86.25\% $\pm$ 1.70 (3)  89.42\% $\pm$ 0.46 (3)
46    67.92\% $\pm$ 3.13 (3)  86.27\% $\pm$ 0.49 (3)  88.89\% $\pm$ 0.79 (3)
47    85.44\% $\pm$ 0.26 (3)  86.94\% $\pm$ 1.47 (3)  90.21\% $\pm$ 0.46 (3)
48    86.01\% $\pm$ 0.40 (3)  86.83\% $\pm$ 0.49 (3)  91.03\% $\pm$ 0.48 (3)
49    83.33\% $\pm$ 0.43 (3)  90.98\% $\pm$ 3.52 (3)  90.14\% $\pm$ 0.52 (3)
50     84.96\% $\pm$ nan (1)   86.55\% $\pm$ nan (1)   90.48\% $\pm$ nan (1)
51    83.46\% $\pm$ 0.75 (3)  86.27\% $\pm$ 0.97 (3)  88.76\% $\pm$ 1.40 (3)

                     method           final_avg_acc                          \
corr                                             50                      75
0                       erm  95.91\% $\pm$ 0.00 (3)  94.94\% $\pm$ 0.13 (3)
1                   erm_dfr                     NaN  97.53\% $\pm$ 0.25 (3)
2                 erm_dfr_2  95.75\% $\pm$ 0.14 (3)  94.55\% $\pm$ 0.13 (3)
3              erm_dfr_gdro                     NaN  96.94\% $\pm$ 0.34 (3)
4            erm_dfr_gdro_2  95.58\% $\pm$ 0.17 (3)  94.33\% $\pm$ 0.17 (3)
5          erm_dfr_gdro_new                     NaN  96.94\% $\pm$ 0.38 (3)
6      erm_dfr_gdro_new_0.1                     NaN                     NaN
7     erm_dfr_gdro_new_0.25                     NaN                     NaN
8      erm_dfr_gdro_new_0.5                     NaN                     NaN
9     erm_dfr_gdro_new_0.75                     NaN                     NaN
10     erm_dfr_gdro_new_0.9                     NaN                     NaN
11              erm_dfr_new                     NaN  96.89\% $\pm$ 0.46 (3)
12           erm_dfr_rw_new                     NaN  97.00\% $\pm$ 0.33 (3)
13       erm_dfr_rw_new_0.1                     NaN                     NaN
14      erm_dfr_rw_new_0.25                     NaN                     NaN
15       erm_dfr_rw_new_0.5                     NaN                     NaN
16      erm_dfr_rw_new_0.75                     NaN                     NaN
17       erm_dfr_rw_new_0.9                     NaN                     NaN
18                 erm_gdro  95.83\% $\pm$ 0.00 (3)  94.69\% $\pm$ 0.17 (3)
19             erm_gdro_0.1                     NaN                     NaN
20            erm_gdro_0.25                     NaN                     NaN
21             erm_gdro_0.5                     NaN                     NaN
22            erm_gdro_0.75                     NaN                     NaN
23             erm_gdro_0.9                     NaN                     NaN
24            erm_gdro_frz0  95.89\% $\pm$ 0.13 (3)  94.88\% $\pm$ 0.19 (3)
25            erm_gdro_frz1  95.91\% $\pm$ 0.08 (3)  94.91\% $\pm$ 0.22 (3)
26            erm_gdro_frz2  95.80\% $\pm$ 0.13 (3)  94.94\% $\pm$ 0.10 (3)
27            erm_gdro_frz3  95.86\% $\pm$ 0.05 (3)  95.02\% $\pm$ 0.13 (3)
28            erm_gdro_frz4  95.97\% $\pm$ 0.13 (3)  95.00\% $\pm$ 0.00 (3)
29        erm_gdro_frz_rst1  95.86\% $\pm$ 0.13 (3)  94.08\% $\pm$ 0.08 (3)
30        erm_gdro_frz_rst2  95.72\% $\pm$ 0.05 (3)  94.16\% $\pm$ 0.14 (3)
31        erm_gdro_frz_rst3  95.83\% $\pm$ 0.17 (3)  94.61\% $\pm$ 0.05 (3)
32        erm_gdro_frz_rst4  95.94\% $\pm$ 0.10 (3)  95.00\% $\pm$ 0.17 (3)
33                   erm_rw  95.77\% $\pm$ 0.13 (3)  94.52\% $\pm$ 0.24 (3)
34               erm_rw_0.1                     NaN                     NaN
35              erm_rw_0.25                     NaN                     NaN
36               erm_rw_0.5                     NaN                     NaN
37              erm_rw_0.75                     NaN                     NaN
38               erm_rw_0.9                     NaN                     NaN
39                     gdro  96.22\% $\pm$ 0.05 (3)  94.97\% $\pm$ 0.13 (3)
40                   gdro_1  95.77\% $\pm$ 0.10 (3)  94.11\% $\pm$ 0.13 (3)
41                 gdro_dfr                     NaN  96.19\% $\pm$ 0.51 (3)
42                 gdro_erm  95.75\% $\pm$ 0.14 (3)  93.88\% $\pm$ 0.29 (3)
43            gdro_erm_frz1  96.39\% $\pm$ 0.10 (3)  95.39\% $\pm$ 0.27 (3)
44            gdro_erm_frz2  96.36\% $\pm$ 0.13 (3)  95.39\% $\pm$ 0.27 (3)
45            gdro_erm_frz3  96.36\% $\pm$ 0.21 (3)  95.39\% $\pm$ 0.27 (3)
46            gdro_erm_frz4  96.25\% $\pm$ 0.14 (3)  95.27\% $\pm$ 0.13 (3)
47                gdro_gdro  94.63\% $\pm$ 0.46 (3)  93.86\% $\pm$ 1.05 (3)
48              gdro_gdro_1  95.44\% $\pm$ 0.19 (3)  93.41\% $\pm$ 0.51 (3)
49            gdro_gdro_dfr                     NaN  95.36\% $\pm$ 0.79 (3)
50                  gdro_rw   95.58\% $\pm$ nan (1)   93.83\% $\pm$ nan (1)
51                   rw_erm  96.05\% $\pm$ 0.05 (3)  95.02\% $\pm$ 0.10 (3)


corr                      95                     625                     875
0     88.49\% $\pm$ 0.30 (3)  95.30\% $\pm$ 0.05 (3)  93.66\% $\pm$ 0.17 (3)
1     94.77\% $\pm$ 0.21 (3)  97.25\% $\pm$ 0.22 (3)  96.27\% $\pm$ 0.32 (3)
2     89.49\% $\pm$ 0.71 (3)  95.16\% $\pm$ 0.08 (3)  93.69\% $\pm$ 0.34 (3)
3     94.52\% $\pm$ 0.68 (3)  97.12\% $\pm$ 0.18 (2)  95.75\% $\pm$ 0.08 (3)
4     89.19\% $\pm$ 0.25 (3)  95.19\% $\pm$ 0.05 (3)  93.77\% $\pm$ 0.34 (3)
5     94.41\% $\pm$ 0.55 (3)  97.00\% $\pm$ 0.29 (3)  96.08\% $\pm$ 0.36 (3)
6     90.69\% $\pm$ 3.37 (3)                     NaN                     NaN
7     92.66\% $\pm$ 1.46 (3)                     NaN                     NaN
8     93.61\% $\pm$ 0.39 (3)                     NaN                     NaN
9     94.36\% $\pm$ 0.82 (3)                     NaN                     NaN
10    94.50\% $\pm$ 0.80 (3)                     NaN                     NaN
11    94.13\% $\pm$ 0.71 (3)  97.08\% $\pm$ 0.22 (3)  96.05\% $\pm$ 0.35 (3)
12    94.33\% $\pm$ 0.30 (3)  97.05\% $\pm$ 0.35 (3)  96.11\% $\pm$ 0.24 (3)
13    90.74\% $\pm$ 3.54 (3)                     NaN                     NaN
14    92.69\% $\pm$ 1.43 (3)                     NaN                     NaN
15    93.58\% $\pm$ 0.36 (3)                     NaN                     NaN
16    94.47\% $\pm$ 0.63 (3)                     NaN                     NaN
17    94.55\% $\pm$ 0.41 (3)                     NaN                     NaN
18    91.08\% $\pm$ 0.29 (3)  95.27\% $\pm$ 0.10 (3)  94.36\% $\pm$ 0.17 (3)
19    87.77\% $\pm$ 0.53 (3)                     NaN                     NaN
20    87.41\% $\pm$ 0.58 (3)                     NaN                     NaN
21    87.80\% $\pm$ 0.27 (3)                     NaN                     NaN
22    90.41\% $\pm$ 0.08 (3)                     NaN                     NaN
23    90.60\% $\pm$ 0.47 (3)                     NaN                     NaN
24    91.30\% $\pm$ 0.17 (3)  95.50\% $\pm$ 0.08 (3)  95.47\% $\pm$ 0.21 (3)
25    91.35\% $\pm$ 0.17 (3)  95.50\% $\pm$ 0.08 (3)  95.50\% $\pm$ 0.22 (3)
26    91.41\% $\pm$ 0.08 (3)  95.58\% $\pm$ 0.08 (3)  95.41\% $\pm$ 0.22 (3)
27    91.44\% $\pm$ 0.21 (3)  95.50\% $\pm$ 0.14 (3)  95.61\% $\pm$ 0.25 (3)
28    91.83\% $\pm$ 0.29 (3)  95.64\% $\pm$ 0.10 (3)  95.19\% $\pm$ 0.13 (3)
29    92.10\% $\pm$ 0.17 (3)  95.13\% $\pm$ 0.17 (3)  95.19\% $\pm$ 0.35 (3)
30    91.99\% $\pm$ 0.30 (3)  95.13\% $\pm$ 0.13 (3)  95.33\% $\pm$ 0.22 (3)
31    91.83\% $\pm$ 0.22 (3)  95.25\% $\pm$ 0.08 (3)  95.41\% $\pm$ 0.08 (3)
32    91.74\% $\pm$ 0.51 (3)  95.61\% $\pm$ 0.13 (3)  95.13\% $\pm$ 0.10 (3)
33    89.32\% $\pm$ 0.33 (3)  95.22\% $\pm$ 0.13 (3)  93.69\% $\pm$ 0.21 (3)
34    87.77\% $\pm$ 0.53 (3)                     NaN                     NaN
35    87.35\% $\pm$ 0.53 (3)                     NaN                     NaN
36    87.57\% $\pm$ 0.44 (3)                     NaN                     NaN
37    88.88\% $\pm$ 0.25 (3)                     NaN                     NaN
38    89.13\% $\pm$ 0.41 (3)                     NaN                     NaN
39    91.35\% $\pm$ 0.13 (3)  95.55\% $\pm$ 0.10 (3)  95.02\% $\pm$ 0.05 (3)
40    91.97\% $\pm$ 0.21 (3)  95.02\% $\pm$ 0.13 (3)  95.13\% $\pm$ 0.32 (3)
41    92.27\% $\pm$ 0.90 (3)  95.50\% $\pm$ 1.12 (3)  95.52\% $\pm$ 0.17 (3)
42    88.41\% $\pm$ 3.11 (3)  93.99\% $\pm$ 2.46 (3)  93.66\% $\pm$ 0.14 (3)
43    91.13\% $\pm$ 0.63 (3)  95.58\% $\pm$ 0.25 (3)  95.33\% $\pm$ 0.17 (3)
44    91.19\% $\pm$ 0.67 (3)  95.64\% $\pm$ 0.05 (3)  95.30\% $\pm$ 0.10 (3)
45    91.21\% $\pm$ 0.63 (3)  95.41\% $\pm$ 0.17 (3)  95.30\% $\pm$ 0.13 (3)
46    91.44\% $\pm$ 0.77 (3)  95.13\% $\pm$ 1.13 (3)  95.83\% $\pm$ 0.08 (3)
47    91.52\% $\pm$ 0.13 (3)  94.75\% $\pm$ 1.16 (3)  93.97\% $\pm$ 0.29 (3)
48    90.91\% $\pm$ 0.38 (3)  93.22\% $\pm$ 3.15 (3)  94.88\% $\pm$ 0.13 (3)
49    90.77\% $\pm$ 1.48 (3)  93.63\% $\pm$ 3.16 (3)  94.11\% $\pm$ 0.46 (3)
50     90.99\% $\pm$ nan (1)   90.99\% $\pm$ nan (1)   95.16\% $\pm$ nan (1)
51    91.52\% $\pm$ 0.65 (3)  95.55\% $\pm$ 0.05 (3)  94.97\% $\pm$ 0.17 (3)

                     method         final_worst_acc                          \
corr                                             50                      75
0                       erm  89.36\% $\pm$ 0.55 (3)  87.95\% $\pm$ 0.63 (3)
1                   erm_dfr                     NaN  88.97\% $\pm$ 0.97 (3)
2                 erm_dfr_2  85.77\% $\pm$ 1.04 (3)  83.28\% $\pm$ 1.32 (3)
3              erm_dfr_gdro                     NaN  90.65\% $\pm$ 0.54 (3)
4            erm_dfr_gdro_2  84.79\% $\pm$ 0.89 (3)  81.68\% $\pm$ 0.74 (3)
5          erm_dfr_gdro_new                     NaN  91.48\% $\pm$ 0.59 (3)
6      erm_dfr_gdro_new_0.1                     NaN                     NaN
7     erm_dfr_gdro_new_0.25                     NaN                     NaN
8      erm_dfr_gdro_new_0.5                     NaN                     NaN
9     erm_dfr_gdro_new_0.75                     NaN                     NaN
10     erm_dfr_gdro_new_0.9                     NaN                     NaN
11              erm_dfr_new                     NaN  90.13\% $\pm$ 0.55 (3)
12           erm_dfr_rw_new                     NaN  91.12\% $\pm$ 0.47 (3)
13       erm_dfr_rw_new_0.1                     NaN                     NaN
14      erm_dfr_rw_new_0.25                     NaN                     NaN
15       erm_dfr_rw_new_0.5                     NaN                     NaN
16      erm_dfr_rw_new_0.75                     NaN                     NaN
17       erm_dfr_rw_new_0.9                     NaN                     NaN
18                 erm_gdro  86.71\% $\pm$ 0.50 (3)  85.20\% $\pm$ 0.56 (3)
19             erm_gdro_0.1                     NaN                     NaN
20            erm_gdro_0.25                     NaN                     NaN
21             erm_gdro_0.5                     NaN                     NaN
22            erm_gdro_0.75                     NaN                     NaN
23             erm_gdro_0.9                     NaN                     NaN
24            erm_gdro_frz0  90.65\% $\pm$ 0.16 (3)  90.24\% $\pm$ 0.09 (3)
25            erm_gdro_frz1  90.60\% $\pm$ 0.09 (3)  90.19\% $\pm$ 0.16 (3)
26            erm_gdro_frz2  90.65\% $\pm$ 0.16 (3)  90.24\% $\pm$ 0.36 (3)
27            erm_gdro_frz3  90.71\% $\pm$ 0.18 (3)  90.45\% $\pm$ 0.32 (3)
28            erm_gdro_frz4  90.60\% $\pm$ 0.24 (3)  90.55\% $\pm$ 0.55 (3)
29        erm_gdro_frz_rst1  90.81\% $\pm$ 0.16 (3)  90.45\% $\pm$ 0.09 (3)
30        erm_gdro_frz_rst2  90.76\% $\pm$ 0.24 (3)  90.29\% $\pm$ 0.24 (3)
31        erm_gdro_frz_rst3  90.45\% $\pm$ 0.36 (3)  89.98\% $\pm$ 0.32 (3)
32        erm_gdro_frz_rst4  90.13\% $\pm$ 0.39 (3)  90.03\% $\pm$ 0.31 (3)
33                   erm_rw  84.32\% $\pm$ 0.78 (3)  82.71\% $\pm$ 0.16 (3)
34               erm_rw_0.1                     NaN                     NaN
35              erm_rw_0.25                     NaN                     NaN
36               erm_rw_0.5                     NaN                     NaN
37              erm_rw_0.75                     NaN                     NaN
38               erm_rw_0.9                     NaN                     NaN
39                     gdro  89.56\% $\pm$ 0.16 (3)  89.72\% $\pm$ 0.41 (3)
40                   gdro_1  90.86\% $\pm$ 0.18 (3)  90.45\% $\pm$ 0.09 (3)
41                 gdro_dfr                     NaN  89.52\% $\pm$ 1.06 (3)
42                 gdro_erm  87.95\% $\pm$ 0.48 (3)  87.28\% $\pm$ 2.03 (3)
43            gdro_erm_frz1  88.32\% $\pm$ 0.00 (3)  87.33\% $\pm$ 0.09 (3)
44            gdro_erm_frz2  88.11\% $\pm$ 0.09 (3)  87.28\% $\pm$ 0.09 (3)
45            gdro_erm_frz3  88.47\% $\pm$ 0.27 (3)  87.69\% $\pm$ 0.27 (3)
46            gdro_erm_frz4  88.58\% $\pm$ 0.45 (3)  88.16\% $\pm$ 0.97 (3)
47                gdro_gdro  90.29\% $\pm$ 0.70 (3)  89.51\% $\pm$ 1.18 (3)
48              gdro_gdro_1  90.71\% $\pm$ 0.24 (3)  90.19\% $\pm$ 0.54 (3)
49            gdro_gdro_dfr                     NaN  91.14\% $\pm$ 0.96 (3)
50                  gdro_rw   91.12\% $\pm$ nan (1)   89.72\% $\pm$ nan (1)
51                   rw_erm  89.62\% $\pm$ 0.24 (3)  89.77\% $\pm$ 0.63 (3)


corr                      95                     625                     875
0     72.95\% $\pm$ 0.36 (3)  89.72\% $\pm$ 0.41 (3)  81.62\% $\pm$ 0.87 (3)
1     80.84\% $\pm$ 1.35 (3)  88.58\% $\pm$ 0.50 (3)  85.51\% $\pm$ 1.95 (3)
2     71.35\% $\pm$ 5.96 (3)  86.76\% $\pm$ 0.82 (3)  78.30\% $\pm$ 3.33 (3)
3     85.36\% $\pm$ 0.81 (3)  91.43\% $\pm$ 0.44 (2)  89.10\% $\pm$ 0.82 (3)
4     69.07\% $\pm$ 6.49 (3)  86.19\% $\pm$ 0.70 (3)  76.43\% $\pm$ 4.37 (3)
5     88.99\% $\pm$ 0.65 (3)  91.43\% $\pm$ 0.41 (3)  90.86\% $\pm$ 0.74 (3)
6     81.15\% $\pm$ 7.18 (3)                     NaN                     NaN
7     85.49\% $\pm$ 2.22 (3)                     NaN                     NaN
8     87.27\% $\pm$ 0.72 (3)                     NaN                     NaN
9     88.72\% $\pm$ 1.15 (3)                     NaN                     NaN
10    89.75\% $\pm$ 0.05 (3)                     NaN                     NaN
11    87.69\% $\pm$ 1.09 (3)  90.76\% $\pm$ 0.09 (3)  89.56\% $\pm$ 0.78 (3)
12    88.89\% $\pm$ 0.78 (3)  91.07\% $\pm$ 0.24 (3)  90.91\% $\pm$ 0.80 (3)
13    81.15\% $\pm$ 7.18 (3)                     NaN                     NaN
14    85.15\% $\pm$ 1.82 (3)                     NaN                     NaN
15    86.89\% $\pm$ 0.45 (3)                     NaN                     NaN
16    88.36\% $\pm$ 1.12 (3)                     NaN                     NaN
17    89.57\% $\pm$ 0.19 (3)                     NaN                     NaN
18    73.78\% $\pm$ 2.92 (3)  87.28\% $\pm$ 0.18 (3)  79.08\% $\pm$ 1.60 (3)
19    53.95\% $\pm$ 2.74 (3)                     NaN                     NaN
20    62.41\% $\pm$ 3.33 (3)                     NaN                     NaN
21    67.74\% $\pm$ 0.68 (3)                     NaN                     NaN
22    73.26\% $\pm$ 3.30 (3)                     NaN                     NaN
23    72.33\% $\pm$ 1.15 (3)                     NaN                     NaN
24    83.80\% $\pm$ 0.62 (3)  91.69\% $\pm$ 0.36 (3)  89.10\% $\pm$ 0.82 (3)
25    83.74\% $\pm$ 0.85 (3)  91.64\% $\pm$ 0.32 (3)  88.89\% $\pm$ 0.99 (3)
26    83.90\% $\pm$ 0.59 (3)  91.80\% $\pm$ 0.09 (3)  89.15\% $\pm$ 0.63 (3)
27    84.48\% $\pm$ 0.80 (3)  91.80\% $\pm$ 0.18 (3)  89.25\% $\pm$ 0.62 (3)
28    84.90\% $\pm$ 0.02 (3)  92.06\% $\pm$ 0.27 (3)  89.04\% $\pm$ 0.24 (3)
29    87.28\% $\pm$ 0.18 (3)  91.59\% $\pm$ 0.16 (3)  89.24\% $\pm$ 0.02 (3)
30    86.65\% $\pm$ 0.08 (3)  91.59\% $\pm$ 0.16 (3)  89.01\% $\pm$ 0.08 (3)
31    85.49\% $\pm$ 0.34 (3)  91.64\% $\pm$ 0.32 (3)  88.53\% $\pm$ 0.09 (3)
32    84.56\% $\pm$ 0.52 (3)  92.06\% $\pm$ 0.27 (3)  88.99\% $\pm$ 0.18 (3)
33    66.20\% $\pm$ 2.16 (3)  86.55\% $\pm$ 0.50 (3)  75.34\% $\pm$ 1.15 (3)
34    49.43\% $\pm$ 1.04 (3)                     NaN                     NaN
35    56.28\% $\pm$ 2.16 (3)                     NaN                     NaN
36    63.29\% $\pm$ 3.33 (3)                     NaN                     NaN
37    66.46\% $\pm$ 2.21 (3)                     NaN                     NaN
38    66.25\% $\pm$ 0.80 (3)                     NaN                     NaN
39    86.14\% $\pm$ 0.88 (3)  91.04\% $\pm$ 0.23 (3)  88.75\% $\pm$ 1.11 (3)
40    87.31\% $\pm$ 0.27 (3)  91.69\% $\pm$ 0.09 (3)  89.30\% $\pm$ 0.09 (3)
41    75.34\% $\pm$ 0.70 (3)  88.11\% $\pm$ 2.66 (3)  88.84\% $\pm$ 0.30 (3)
42    66.61\% $\pm$ 2.96 (3)  87.51\% $\pm$ 3.85 (3)  87.73\% $\pm$ 0.21 (3)
43    73.10\% $\pm$ 2.18 (3)  91.11\% $\pm$ 0.54 (3)  84.89\% $\pm$ 0.41 (3)
44    73.16\% $\pm$ 1.56 (3)  91.07\% $\pm$ 0.24 (3)  84.89\% $\pm$ 0.41 (3)
45    73.00\% $\pm$ 1.00 (3)  91.17\% $\pm$ 0.18 (3)  84.79\% $\pm$ 0.59 (3)
46    71.60\% $\pm$ 1.31 (3)  90.33\% $\pm$ 0.96 (3)  84.84\% $\pm$ 0.32 (3)
47    87.08\% $\pm$ 0.29 (3)  90.19\% $\pm$ 0.82 (3)  89.15\% $\pm$ 0.32 (3)
48    87.46\% $\pm$ 0.22 (3)  90.44\% $\pm$ 2.40 (3)  88.89\% $\pm$ 0.32 (3)
49    83.33\% $\pm$ 1.33 (3)  89.08\% $\pm$ 3.15 (3)  90.17\% $\pm$ 0.42 (3)
50     87.18\% $\pm$ nan (1)   87.32\% $\pm$ nan (1)   88.47\% $\pm$ nan (1)
51    86.31\% $\pm$ 0.30 (3)  90.91\% $\pm$ 0.50 (3)  88.06\% $\pm$ 1.64 (3)

                     method           final_avg_acc                          \
corr                                             50                      75
0                       erm  96.20\% $\pm$ 0.12 (3)  95.50\% $\pm$ 0.06 (3)
1                   erm_dfr                     NaN  95.73\% $\pm$ 0.11 (3)
2                 erm_dfr_2  96.06\% $\pm$ 0.11 (3)  95.21\% $\pm$ 0.21 (3)
3              erm_dfr_gdro                     NaN  95.33\% $\pm$ 0.30 (3)
4            erm_dfr_gdro_2  96.00\% $\pm$ 0.10 (3)  95.13\% $\pm$ 0.19 (3)
5          erm_dfr_gdro_new                     NaN  95.24\% $\pm$ 0.21 (3)
6      erm_dfr_gdro_new_0.1                     NaN                     NaN
7     erm_dfr_gdro_new_0.25                     NaN                     NaN
8      erm_dfr_gdro_new_0.5                     NaN                     NaN
9     erm_dfr_gdro_new_0.75                     NaN                     NaN
10     erm_dfr_gdro_new_0.9                     NaN                     NaN
11              erm_dfr_new                     NaN  95.25\% $\pm$ 0.19 (3)
12           erm_dfr_rw_new                     NaN  95.28\% $\pm$ 0.25 (3)
13       erm_dfr_rw_new_0.1                     NaN                     NaN
14      erm_dfr_rw_new_0.25                     NaN                     NaN
15       erm_dfr_rw_new_0.5                     NaN                     NaN
16      erm_dfr_rw_new_0.75                     NaN                     NaN
17       erm_dfr_rw_new_0.9                     NaN                     NaN
18                 erm_gdro  96.01\% $\pm$ 0.06 (3)  95.37\% $\pm$ 0.06 (3)
19             erm_gdro_0.1                     NaN                     NaN
20            erm_gdro_0.25                     NaN                     NaN
21             erm_gdro_0.5                     NaN                     NaN
22            erm_gdro_0.75                     NaN                     NaN
23             erm_gdro_0.9                     NaN                     NaN
24            erm_gdro_frz0  96.16\% $\pm$ 0.10 (3)  95.70\% $\pm$ 0.06 (3)
25            erm_gdro_frz1  96.17\% $\pm$ 0.08 (3)  95.74\% $\pm$ 0.05 (3)
26            erm_gdro_frz2  96.17\% $\pm$ 0.06 (3)  95.73\% $\pm$ 0.06 (3)
27            erm_gdro_frz3  96.18\% $\pm$ 0.05 (3)  95.70\% $\pm$ 0.08 (3)
28            erm_gdro_frz4  96.17\% $\pm$ 0.13 (3)  95.69\% $\pm$ 0.05 (3)
29        erm_gdro_frz_rst1  95.61\% $\pm$ 0.11 (3)  95.27\% $\pm$ 0.08 (3)
30        erm_gdro_frz_rst2  95.70\% $\pm$ 0.07 (3)  95.21\% $\pm$ 0.07 (3)
31        erm_gdro_frz_rst3  95.88\% $\pm$ 0.07 (3)  95.41\% $\pm$ 0.10 (3)
32        erm_gdro_frz_rst4  96.17\% $\pm$ 0.11 (3)  95.60\% $\pm$ 0.05 (3)
33                   erm_rw  95.94\% $\pm$ 0.06 (3)  95.25\% $\pm$ 0.10 (3)
34               erm_rw_0.1                     NaN                     NaN
35              erm_rw_0.25                     NaN                     NaN
36               erm_rw_0.5                     NaN                     NaN
37              erm_rw_0.75                     NaN                     NaN
38               erm_rw_0.9                     NaN                     NaN
39                     gdro  96.36\% $\pm$ 0.14 (3)  95.78\% $\pm$ 0.04 (3)
40                   gdro_1  95.62\% $\pm$ 0.10 (3)  95.24\% $\pm$ 0.02 (3)
41                 gdro_dfr                     NaN  95.26\% $\pm$ 0.11 (3)
42                 gdro_erm  95.79\% $\pm$ 0.09 (3)  94.76\% $\pm$ 0.11 (3)
43            gdro_erm_frz1  96.21\% $\pm$ 0.05 (3)  95.60\% $\pm$ 0.12 (3)
44            gdro_erm_frz2  96.20\% $\pm$ 0.05 (3)  95.59\% $\pm$ 0.11 (3)
45            gdro_erm_frz3  96.24\% $\pm$ 0.08 (3)  95.63\% $\pm$ 0.10 (3)
46            gdro_erm_frz4  96.31\% $\pm$ 0.05 (3)  95.86\% $\pm$ 0.09 (3)
47                gdro_gdro  94.51\% $\pm$ 0.66 (3)  94.97\% $\pm$ 0.80 (3)
48              gdro_gdro_1  95.25\% $\pm$ 0.29 (3)  94.96\% $\pm$ 0.27 (3)
49            gdro_gdro_dfr                     NaN  93.97\% $\pm$ 0.25 (3)
50                  gdro_rw   95.69\% $\pm$ nan (1)   95.15\% $\pm$ nan (1)
51                   rw_erm  96.39\% $\pm$ 0.14 (3)  95.80\% $\pm$ 0.10 (3)


corr                      95                     625                     875
0     88.49\% $\pm$ 0.14 (3)  96.17\% $\pm$ 0.12 (3)  93.72\% $\pm$ 0.21 (3)
1     94.01\% $\pm$ 0.15 (3)  95.77\% $\pm$ 0.28 (3)  95.26\% $\pm$ 0.04 (3)
2     90.32\% $\pm$ 0.22 (3)  95.92\% $\pm$ 0.25 (3)  94.03\% $\pm$ 0.07 (3)
3     93.27\% $\pm$ 0.25 (3)  95.79\% $\pm$ 0.12 (2)  94.57\% $\pm$ 0.11 (3)
4     90.20\% $\pm$ 0.31 (3)  95.88\% $\pm$ 0.22 (3)  94.00\% $\pm$ 0.01 (3)
5     93.27\% $\pm$ 0.26 (3)  95.39\% $\pm$ 0.29 (3)  94.85\% $\pm$ 0.43 (3)
6     88.93\% $\pm$ 4.30 (3)                     NaN                     NaN
7     91.16\% $\pm$ 1.59 (3)                     NaN                     NaN
8     92.16\% $\pm$ 0.76 (3)                     NaN                     NaN
9     93.00\% $\pm$ 0.46 (3)                     NaN                     NaN
10    93.25\% $\pm$ 0.47 (3)                     NaN                     NaN
11    92.80\% $\pm$ 0.63 (3)  95.47\% $\pm$ 0.23 (3)  94.82\% $\pm$ 0.39 (3)
12    93.25\% $\pm$ 0.22 (3)  95.43\% $\pm$ 0.27 (3)  94.97\% $\pm$ 0.30 (3)
13    88.83\% $\pm$ 4.47 (3)                     NaN                     NaN
14    91.19\% $\pm$ 1.73 (3)                     NaN                     NaN
15    92.12\% $\pm$ 0.74 (3)                     NaN                     NaN
16    92.99\% $\pm$ 0.36 (3)                     NaN                     NaN
17    93.27\% $\pm$ 0.37 (3)                     NaN                     NaN
18    92.11\% $\pm$ 0.15 (3)  95.97\% $\pm$ 0.11 (3)  94.59\% $\pm$ 0.13 (3)
19    89.01\% $\pm$ 0.36 (3)                     NaN                     NaN
20    88.68\% $\pm$ 0.36 (3)                     NaN                     NaN
21    88.72\% $\pm$ 0.19 (3)                     NaN                     NaN
22    91.22\% $\pm$ 0.18 (3)                     NaN                     NaN
23    91.54\% $\pm$ 0.42 (3)                     NaN                     NaN
24    92.08\% $\pm$ 0.37 (3)  96.17\% $\pm$ 0.06 (3)  95.38\% $\pm$ 0.12 (3)
25    92.10\% $\pm$ 0.42 (3)  96.17\% $\pm$ 0.06 (3)  95.40\% $\pm$ 0.15 (3)
26    92.20\% $\pm$ 0.32 (3)  96.20\% $\pm$ 0.09 (3)  95.35\% $\pm$ 0.10 (3)
27    92.13\% $\pm$ 0.40 (3)  96.17\% $\pm$ 0.06 (3)  95.29\% $\pm$ 0.07 (3)
28    92.52\% $\pm$ 0.24 (3)  96.05\% $\pm$ 0.12 (3)  95.27\% $\pm$ 0.08 (3)
29    92.98\% $\pm$ 0.10 (3)  95.79\% $\pm$ 0.08 (3)  94.75\% $\pm$ 0.09 (3)
30    92.77\% $\pm$ 0.06 (3)  95.88\% $\pm$ 0.04 (3)  94.75\% $\pm$ 0.12 (3)
31    92.72\% $\pm$ 0.14 (3)  96.02\% $\pm$ 0.06 (3)  94.93\% $\pm$ 0.13 (3)
32    92.18\% $\pm$ 0.32 (3)  95.99\% $\pm$ 0.11 (3)  95.04\% $\pm$ 0.15 (3)
33    90.25\% $\pm$ 0.26 (3)  95.95\% $\pm$ 0.10 (3)  93.99\% $\pm$ 0.22 (3)
34    88.99\% $\pm$ 0.34 (3)                     NaN                     NaN
35    88.71\% $\pm$ 0.39 (3)                     NaN                     NaN
36    88.65\% $\pm$ 0.23 (3)                     NaN                     NaN
37    89.86\% $\pm$ 0.33 (3)                     NaN                     NaN
38    90.17\% $\pm$ 0.34 (3)                     NaN                     NaN
39    91.87\% $\pm$ 0.38 (3)  96.38\% $\pm$ 0.05 (3)  94.72\% $\pm$ 0.03 (3)
40    92.87\% $\pm$ 0.08 (3)  95.69\% $\pm$ 0.09 (3)  94.75\% $\pm$ 0.08 (3)
41    92.24\% $\pm$ 0.55 (3)  94.24\% $\pm$ 1.95 (3)  94.82\% $\pm$ 0.31 (3)
42    88.94\% $\pm$ 2.99 (3)  93.83\% $\pm$ 2.80 (3)  93.34\% $\pm$ 0.11 (3)
43    91.76\% $\pm$ 0.95 (3)  96.14\% $\pm$ 0.36 (3)  94.65\% $\pm$ 0.08 (3)
44    91.78\% $\pm$ 0.94 (3)  96.17\% $\pm$ 0.33 (3)  94.67\% $\pm$ 0.10 (3)
45    91.80\% $\pm$ 0.94 (3)  96.13\% $\pm$ 0.39 (3)  94.72\% $\pm$ 0.11 (3)
46    92.00\% $\pm$ 0.97 (3)  95.79\% $\pm$ 1.32 (3)  95.10\% $\pm$ 0.07 (3)
47    92.16\% $\pm$ 0.28 (3)  95.56\% $\pm$ 1.33 (3)  93.23\% $\pm$ 0.03 (3)
48    91.58\% $\pm$ 0.63 (3)  93.64\% $\pm$ 3.07 (3)  94.69\% $\pm$ 0.04 (3)
49    90.61\% $\pm$ 0.88 (3)  91.65\% $\pm$ 4.40 (3)  92.84\% $\pm$ 0.54 (3)
50     91.68\% $\pm$ nan (1)   91.65\% $\pm$ nan (1)   94.75\% $\pm$ nan (1)
51    92.11\% $\pm$ 0.40 (3)  96.35\% $\pm$ 0.08 (3)  94.74\% $\pm$ 0.03 (3)

In [24]:
dataset = "CUB"
results = dict()
splits = ['val','test']
for s in splits:
    results[s] =create_results_table(dataset, s)
    display(create_final_table(results[s]['means'],"worst_acc"))
    display(create_final_table(results[s]['means'],"avg_acc"))

          method         final_worst_acc                          \
corr                                  75                      95
0         gdro_1  89.86\% $\pm$ 0.00 (3)  85.98\% $\pm$ 0.44 (3)
1     jtt_60_100  79.64\% $\pm$ 0.77 (3)  35.59\% $\pm$ 4.28 (3)


corr                     625                     875
0     86.53\% $\pm$ 0.84 (3)  90.48\% $\pm$ 0.00 (3)
1     79.83\% $\pm$ 1.46 (3)  62.70\% $\pm$ 2.38 (3)

          method           final_avg_acc                          \
corr                                  75                      95
0         gdro_1  94.11\% $\pm$ 0.13 (3)  91.97\% $\pm$ 0.21 (3)
1     jtt_60_100  93.55\% $\pm$ 0.19 (3)  79.43\% $\pm$ 1.56 (3)


corr                     625                     875
0     95.02\% $\pm$ 0.13 (3)  95.13\% $\pm$ 0.32 (3)
1     94.88\% $\pm$ 0.13 (3)  91.33\% $\pm$ 0.22 (3)

          method         final_worst_acc                          \
corr                                  75                      95
0         gdro_1  90.45\% $\pm$ 0.09 (3)  87.31\% $\pm$ 0.27 (3)
1     jtt_60_100  78.76\% $\pm$ 0.59 (3)  35.10\% $\pm$ 5.37 (3)


corr                     625                     875
0     91.69\% $\pm$ 0.09 (3)  89.30\% $\pm$ 0.09 (3)
1     83.96\% $\pm$ 0.95 (3)  62.62\% $\pm$ 3.01 (3)

          method           final_avg_acc                          \
corr                                  75                      95
0         gdro_1  95.24\% $\pm$ 0.02 (3)  92.87\% $\pm$ 0.08 (3)
1     jtt_60_100  94.64\% $\pm$ 0.10 (3)  80.29\% $\pm$ 1.76 (3)


corr                     625                     875
0     95.69\% $\pm$ 0.09 (3)  94.75\% $\pm$ 0.08 (3)
1     95.52\% $\pm$ 0.03 (3)  90.93\% $\pm$ 0.36 (3)

In [7]:
dataset = "CUB"
results = dict()
splits = ['val','test']
for s in splits:
    results[s] =create_results_table(dataset, s)
    display(create_final_table(results[s]['means'],"worst_acc"))
    display(create_final_table(results[s]['means'],"avg_acc"))

                     method         final_worst_acc                          \
corr                                             50                      75
0                       erm  87.31\% $\pm$ 1.29 (3)  88.81\% $\pm$ 1.03 (3)
1                   erm_dfr                     NaN  92.79\% $\pm$ 0.86 (3)
2                 erm_dfr_2  83.08\% $\pm$ 0.43 (3)  83.22\% $\pm$ 0.67 (3)
3              erm_dfr_gdro                     NaN  94.53\% $\pm$ 0.86 (3)
4            erm_dfr_gdro_2  82.09\% $\pm$ 1.29 (3)  80.98\% $\pm$ 0.77 (3)
5          erm_dfr_gdro_new                     NaN  95.27\% $\pm$ 0.43 (3)
6      erm_dfr_gdro_new_0.1                     NaN                     NaN
7     erm_dfr_gdro_new_0.25                     NaN                     NaN
8      erm_dfr_gdro_new_0.5                     NaN                     NaN
9     erm_dfr_gdro_new_0.75                     NaN                     NaN
10     erm_dfr_gdro_new_0.9                     NaN                     NaN
11              erm_dfr_new                     NaN  94.83\% $\pm$ 0.04 (3)
12           erm_dfr_rw_new                     NaN  95.11\% $\pm$ 0.36 (3)
13       erm_dfr_rw_new_0.1                     NaN                     NaN
14      erm_dfr_rw_new_0.25                     NaN                     NaN
15       erm_dfr_rw_new_0.5                     NaN                     NaN
16      erm_dfr_rw_new_0.75                     NaN                     NaN
17       erm_dfr_rw_new_0.9                     NaN                     NaN
18                 erm_gdro  82.59\% $\pm$ 0.43 (3)  85.01\% $\pm$ 0.77 (3)
19             erm_gdro_0.1                     NaN                     NaN
20            erm_gdro_0.25                     NaN                     NaN
21             erm_gdro_0.5                     NaN                     NaN
22            erm_gdro_0.75                     NaN                     NaN
23             erm_gdro_0.9                     NaN                     NaN
24            erm_gdro_frz0  90.05\% $\pm$ 1.55 (3)  90.81\% $\pm$ 0.35 (3)
25            erm_gdro_frz1  90.30\% $\pm$ 1.29 (3)  90.81\% $\pm$ 0.35 (3)
26            erm_gdro_frz2  89.55\% $\pm$ 1.97 (3)  90.78\% $\pm$ 0.30 (3)
27            erm_gdro_frz3  89.55\% $\pm$ 2.24 (3)  91.05\% $\pm$ 0.39 (3)
28            erm_gdro_frz4  91.29\% $\pm$ 0.43 (3)  91.44\% $\pm$ 0.39 (3)
29        erm_gdro_frz_rst1  90.55\% $\pm$ 0.43 (3)  89.86\% $\pm$ 0.00 (3)
30        erm_gdro_frz_rst2  89.80\% $\pm$ 0.43 (3)  89.64\% $\pm$ 0.72 (3)
31        erm_gdro_frz_rst3  89.30\% $\pm$ 0.86 (3)  90.54\% $\pm$ 0.00 (3)
32        erm_gdro_frz_rst4  92.04\% $\pm$ 0.43 (3)  91.67\% $\pm$ 0.39 (3)
33                   erm_rw  81.09\% $\pm$ 0.43 (3)  82.33\% $\pm$ 0.77 (3)
34               erm_rw_0.1                     NaN                     NaN
35              erm_rw_0.25                     NaN                     NaN
36               erm_rw_0.5                     NaN                     NaN
37              erm_rw_0.75                     NaN                     NaN
38               erm_rw_0.9                     NaN                     NaN
39                     gdro  88.81\% $\pm$ 1.29 (3)  88.76\% $\pm$ 0.43 (3)
40                   gdro_1  90.80\% $\pm$ 0.43 (3)  89.86\% $\pm$ 0.00 (3)
41                 gdro_dfr                     NaN  90.28\% $\pm$ 2.68 (3)
42                 gdro_erm  85.32\% $\pm$ 1.14 (3)  88.32\% $\pm$ 0.76 (3)
43            gdro_erm_frz1  88.31\% $\pm$ 0.86 (3)  86.58\% $\pm$ 0.67 (3)
44            gdro_erm_frz2  88.31\% $\pm$ 0.86 (3)  86.80\% $\pm$ 0.77 (3)
45            gdro_erm_frz3  88.31\% $\pm$ 0.86 (3)  87.02\% $\pm$ 0.39 (3)
46            gdro_erm_frz4  87.31\% $\pm$ 0.75 (3)  89.04\% $\pm$ 0.39 (3)
47                gdro_gdro  90.30\% $\pm$ 1.29 (3)  89.21\% $\pm$ 0.04 (3)
48              gdro_gdro_1  91.04\% $\pm$ 0.00 (3)  90.09\% $\pm$ 0.39 (3)
49            gdro_gdro_dfr                     NaN  93.22\% $\pm$ 1.96 (3)
50                  gdro_rw   91.79\% $\pm$ nan (1)   90.47\% $\pm$ nan (1)
51                   rw_erm  88.81\% $\pm$ 1.29 (3)  88.79\% $\pm$ 0.41 (3)


corr                      95                     625                     875
0     69.17\% $\pm$ 0.75 (3)  85.99\% $\pm$ 0.49 (3)  83.33\% $\pm$ 0.79 (3)
1     82.16\% $\pm$ 2.02 (3)  92.29\% $\pm$ 1.14 (3)  87.56\% $\pm$ 3.45 (3)
2     68.00\% $\pm$ 5.59 (3)  83.47\% $\pm$ 0.49 (3)  79.10\% $\pm$ 3.58 (3)
3     87.06\% $\pm$ 1.72 (3)  95.15\% $\pm$ 0.53 (2)  90.80\% $\pm$ 2.15 (3)
4     66.15\% $\pm$ 6.04 (3)  82.63\% $\pm$ 0.49 (3)  76.98\% $\pm$ 4.20 (3)
5     89.80\% $\pm$ 1.14 (3)  95.65\% $\pm$ 0.44 (3)  94.28\% $\pm$ 0.86 (3)
6     83.34\% $\pm$ 5.66 (3)                     NaN                     NaN
7     87.54\% $\pm$ 2.78 (3)                     NaN                     NaN
8     89.06\% $\pm$ 1.87 (3)                     NaN                     NaN
9     90.66\% $\pm$ 1.62 (3)                     NaN                     NaN
10    91.38\% $\pm$ 0.71 (3)                     NaN                     NaN
11    89.30\% $\pm$ 1.14 (3)  95.27\% $\pm$ 0.86 (3)  93.78\% $\pm$ 0.43 (3)
12    89.60\% $\pm$ 1.56 (3)  95.52\% $\pm$ 0.75 (3)  94.23\% $\pm$ 0.82 (3)
13    83.49\% $\pm$ 5.86 (3)                     NaN                     NaN
14    87.32\% $\pm$ 2.58 (3)                     NaN                     NaN
15    89.05\% $\pm$ 1.88 (3)                     NaN                     NaN
16    90.49\% $\pm$ 1.48 (3)                     NaN                     NaN
17    90.85\% $\pm$ 0.48 (3)                     NaN                     NaN
18    69.67\% $\pm$ 3.55 (3)  83.75\% $\pm$ 0.49 (3)  81.75\% $\pm$ 0.00 (3)
19    46.62\% $\pm$ 1.50 (3)                     NaN                     NaN
20    57.64\% $\pm$ 2.42 (3)                     NaN                     NaN
21    65.57\% $\pm$ 2.17 (3)                     NaN                     NaN
22    68.92\% $\pm$ 3.04 (3)                     NaN                     NaN
23    68.17\% $\pm$ 0.43 (3)                     NaN                     NaN
24    82.11\% $\pm$ 0.14 (3)  87.11\% $\pm$ 0.49 (3)  90.48\% $\pm$ 1.59 (3)
25    81.90\% $\pm$ 0.12 (3)  87.11\% $\pm$ 0.49 (3)  90.48\% $\pm$ 1.59 (3)
26    82.50\% $\pm$ 0.47 (3)  87.39\% $\pm$ 0.84 (3)  90.64\% $\pm$ 1.54 (3)
27    81.97\% $\pm$ 0.57 (3)  87.58\% $\pm$ 0.58 (3)  90.74\% $\pm$ 0.92 (3)
28    84.29\% $\pm$ 1.41 (3)  89.83\% $\pm$ 0.00 (3)  90.49\% $\pm$ 0.02 (3)
29    85.55\% $\pm$ 0.12 (3)  86.80\% $\pm$ 0.94 (3)  91.01\% $\pm$ 0.46 (3)
30    84.65\% $\pm$ 0.40 (3)  86.55\% $\pm$ 0.84 (3)  90.74\% $\pm$ 0.46 (3)
31    83.61\% $\pm$ 0.26 (3)  87.39\% $\pm$ 0.84 (3)  91.30\% $\pm$ 0.05 (3)
32    83.21\% $\pm$ 1.74 (3)  90.11\% $\pm$ 0.49 (3)  90.21\% $\pm$ 0.46 (3)
33    61.65\% $\pm$ 0.75 (3)  83.19\% $\pm$ 0.00 (3)  77.78\% $\pm$ 0.79 (3)
34    42.61\% $\pm$ 0.43 (3)                     NaN                     NaN
35    50.13\% $\pm$ 0.87 (3)                     NaN                     NaN
36    57.39\% $\pm$ 5.12 (3)                     NaN                     NaN
37    62.16\% $\pm$ 1.15 (3)                     NaN                     NaN
38    62.16\% $\pm$ 2.30 (3)                     NaN                     NaN
39    82.21\% $\pm$ 0.43 (3)  86.55\% $\pm$ 0.84 (3)  89.15\% $\pm$ 1.21 (3)
40    85.98\% $\pm$ 0.44 (3)  86.53\% $\pm$ 0.84 (3)  90.48\% $\pm$ 0.00 (3)
41    74.63\% $\pm$ 1.29 (3)  89.38\% $\pm$ 3.38 (3)  89.35\% $\pm$ 0.48 (3)
42    62.66\% $\pm$ 3.04 (3)  84.03\% $\pm$ 1.46 (3)  88.94\% $\pm$ 0.80 (3)
43    69.42\% $\pm$ 1.89 (3)  86.27\% $\pm$ 2.57 (3)  89.15\% $\pm$ 0.46 (3)
44    69.67\% $\pm$ 1.15 (3)  86.27\% $\pm$ 2.57 (3)  89.15\% $\pm$ 0.46 (3)
45    69.42\% $\pm$ 1.15 (3)  86.25\% $\pm$ 1.70 (3)  89.42\% $\pm$ 0.46 (3)
46    67.92\% $\pm$ 3.13 (3)  86.27\% $\pm$ 0.49 (3)  88.89\% $\pm$ 0.79 (3)
47    85.44\% $\pm$ 0.26 (3)  86.94\% $\pm$ 1.47 (3)  90.21\% $\pm$ 0.46 (3)
48    86.01\% $\pm$ 0.40 (3)  86.83\% $\pm$ 0.49 (3)  91.03\% $\pm$ 0.48 (3)
49    83.33\% $\pm$ 0.43 (3)  90.98\% $\pm$ 3.52 (3)  90.14\% $\pm$ 0.52 (3)
50     84.96\% $\pm$ nan (1)   86.55\% $\pm$ nan (1)   90.48\% $\pm$ nan (1)
51    83.46\% $\pm$ 0.75 (3)  86.27\% $\pm$ 0.97 (3)  88.76\% $\pm$ 1.40 (3)

                     method           final_avg_acc                          \
corr                                             50                      75
0                       erm  95.91\% $\pm$ 0.00 (3)  94.94\% $\pm$ 0.13 (3)
1                   erm_dfr                     NaN  97.53\% $\pm$ 0.25 (3)
2                 erm_dfr_2  95.75\% $\pm$ 0.14 (3)  94.55\% $\pm$ 0.13 (3)
3              erm_dfr_gdro                     NaN  96.94\% $\pm$ 0.34 (3)
4            erm_dfr_gdro_2  95.58\% $\pm$ 0.17 (3)  94.33\% $\pm$ 0.17 (3)
5          erm_dfr_gdro_new                     NaN  96.94\% $\pm$ 0.38 (3)
6      erm_dfr_gdro_new_0.1                     NaN                     NaN
7     erm_dfr_gdro_new_0.25                     NaN                     NaN
8      erm_dfr_gdro_new_0.5                     NaN                     NaN
9     erm_dfr_gdro_new_0.75                     NaN                     NaN
10     erm_dfr_gdro_new_0.9                     NaN                     NaN
11              erm_dfr_new                     NaN  96.89\% $\pm$ 0.46 (3)
12           erm_dfr_rw_new                     NaN  97.00\% $\pm$ 0.33 (3)
13       erm_dfr_rw_new_0.1                     NaN                     NaN
14      erm_dfr_rw_new_0.25                     NaN                     NaN
15       erm_dfr_rw_new_0.5                     NaN                     NaN
16      erm_dfr_rw_new_0.75                     NaN                     NaN
17       erm_dfr_rw_new_0.9                     NaN                     NaN
18                 erm_gdro  95.83\% $\pm$ 0.00 (3)  94.69\% $\pm$ 0.17 (3)
19             erm_gdro_0.1                     NaN                     NaN
20            erm_gdro_0.25                     NaN                     NaN
21             erm_gdro_0.5                     NaN                     NaN
22            erm_gdro_0.75                     NaN                     NaN
23             erm_gdro_0.9                     NaN                     NaN
24            erm_gdro_frz0  95.89\% $\pm$ 0.13 (3)  94.88\% $\pm$ 0.19 (3)
25            erm_gdro_frz1  95.91\% $\pm$ 0.08 (3)  94.91\% $\pm$ 0.22 (3)
26            erm_gdro_frz2  95.80\% $\pm$ 0.13 (3)  94.94\% $\pm$ 0.10 (3)
27            erm_gdro_frz3  95.86\% $\pm$ 0.05 (3)  95.02\% $\pm$ 0.13 (3)
28            erm_gdro_frz4  95.97\% $\pm$ 0.13 (3)  95.00\% $\pm$ 0.00 (3)
29        erm_gdro_frz_rst1  95.86\% $\pm$ 0.13 (3)  94.08\% $\pm$ 0.08 (3)
30        erm_gdro_frz_rst2  95.72\% $\pm$ 0.05 (3)  94.16\% $\pm$ 0.14 (3)
31        erm_gdro_frz_rst3  95.83\% $\pm$ 0.17 (3)  94.61\% $\pm$ 0.05 (3)
32        erm_gdro_frz_rst4  95.94\% $\pm$ 0.10 (3)  95.00\% $\pm$ 0.17 (3)
33                   erm_rw  95.77\% $\pm$ 0.13 (3)  94.52\% $\pm$ 0.24 (3)
34               erm_rw_0.1                     NaN                     NaN
35              erm_rw_0.25                     NaN                     NaN
36               erm_rw_0.5                     NaN                     NaN
37              erm_rw_0.75                     NaN                     NaN
38               erm_rw_0.9                     NaN                     NaN
39                     gdro  96.22\% $\pm$ 0.05 (3)  94.97\% $\pm$ 0.13 (3)
40                   gdro_1  95.77\% $\pm$ 0.10 (3)  94.11\% $\pm$ 0.13 (3)
41                 gdro_dfr                     NaN  96.19\% $\pm$ 0.51 (3)
42                 gdro_erm  95.75\% $\pm$ 0.14 (3)  93.88\% $\pm$ 0.29 (3)
43            gdro_erm_frz1  96.39\% $\pm$ 0.10 (3)  95.39\% $\pm$ 0.27 (3)
44            gdro_erm_frz2  96.36\% $\pm$ 0.13 (3)  95.39\% $\pm$ 0.27 (3)
45            gdro_erm_frz3  96.36\% $\pm$ 0.21 (3)  95.39\% $\pm$ 0.27 (3)
46            gdro_erm_frz4  96.25\% $\pm$ 0.14 (3)  95.27\% $\pm$ 0.13 (3)
47                gdro_gdro  94.63\% $\pm$ 0.46 (3)  93.86\% $\pm$ 1.05 (3)
48              gdro_gdro_1  95.44\% $\pm$ 0.19 (3)  93.41\% $\pm$ 0.51 (3)
49            gdro_gdro_dfr                     NaN  95.36\% $\pm$ 0.79 (3)
50                  gdro_rw   95.58\% $\pm$ nan (1)   93.83\% $\pm$ nan (1)
51                   rw_erm  96.05\% $\pm$ 0.05 (3)  95.02\% $\pm$ 0.10 (3)


corr                      95                     625                     875
0     88.49\% $\pm$ 0.30 (3)  95.30\% $\pm$ 0.05 (3)  93.66\% $\pm$ 0.17 (3)
1     94.77\% $\pm$ 0.21 (3)  97.25\% $\pm$ 0.22 (3)  96.27\% $\pm$ 0.32 (3)
2     89.49\% $\pm$ 0.71 (3)  95.16\% $\pm$ 0.08 (3)  93.69\% $\pm$ 0.34 (3)
3     94.52\% $\pm$ 0.68 (3)  97.12\% $\pm$ 0.18 (2)  95.75\% $\pm$ 0.08 (3)
4     89.19\% $\pm$ 0.25 (3)  95.19\% $\pm$ 0.05 (3)  93.77\% $\pm$ 0.34 (3)
5     94.41\% $\pm$ 0.55 (3)  97.00\% $\pm$ 0.29 (3)  96.08\% $\pm$ 0.36 (3)
6     90.69\% $\pm$ 3.37 (3)                     NaN                     NaN
7     92.66\% $\pm$ 1.46 (3)                     NaN                     NaN
8     93.61\% $\pm$ 0.39 (3)                     NaN                     NaN
9     94.36\% $\pm$ 0.82 (3)                     NaN                     NaN
10    94.50\% $\pm$ 0.80 (3)                     NaN                     NaN
11    94.13\% $\pm$ 0.71 (3)  97.08\% $\pm$ 0.22 (3)  96.05\% $\pm$ 0.35 (3)
12    94.33\% $\pm$ 0.30 (3)  97.05\% $\pm$ 0.35 (3)  96.11\% $\pm$ 0.24 (3)
13    90.74\% $\pm$ 3.54 (3)                     NaN                     NaN
14    92.69\% $\pm$ 1.43 (3)                     NaN                     NaN
15    93.58\% $\pm$ 0.36 (3)                     NaN                     NaN
16    94.47\% $\pm$ 0.63 (3)                     NaN                     NaN
17    94.55\% $\pm$ 0.41 (3)                     NaN                     NaN
18    91.08\% $\pm$ 0.29 (3)  95.27\% $\pm$ 0.10 (3)  94.36\% $\pm$ 0.17 (3)
19    87.77\% $\pm$ 0.53 (3)                     NaN                     NaN
20    87.41\% $\pm$ 0.58 (3)                     NaN                     NaN
21    87.80\% $\pm$ 0.27 (3)                     NaN                     NaN
22    90.41\% $\pm$ 0.08 (3)                     NaN                     NaN
23    90.60\% $\pm$ 0.47 (3)                     NaN                     NaN
24    91.30\% $\pm$ 0.17 (3)  95.50\% $\pm$ 0.08 (3)  95.47\% $\pm$ 0.21 (3)
25    91.35\% $\pm$ 0.17 (3)  95.50\% $\pm$ 0.08 (3)  95.50\% $\pm$ 0.22 (3)
26    91.41\% $\pm$ 0.08 (3)  95.58\% $\pm$ 0.08 (3)  95.41\% $\pm$ 0.22 (3)
27    91.44\% $\pm$ 0.21 (3)  95.50\% $\pm$ 0.14 (3)  95.61\% $\pm$ 0.25 (3)
28    91.83\% $\pm$ 0.29 (3)  95.64\% $\pm$ 0.10 (3)  95.19\% $\pm$ 0.13 (3)
29    92.10\% $\pm$ 0.17 (3)  95.13\% $\pm$ 0.17 (3)  95.19\% $\pm$ 0.35 (3)
30    91.99\% $\pm$ 0.30 (3)  95.13\% $\pm$ 0.13 (3)  95.33\% $\pm$ 0.22 (3)
31    91.83\% $\pm$ 0.22 (3)  95.25\% $\pm$ 0.08 (3)  95.41\% $\pm$ 0.08 (3)
32    91.74\% $\pm$ 0.51 (3)  95.61\% $\pm$ 0.13 (3)  95.13\% $\pm$ 0.10 (3)
33    89.32\% $\pm$ 0.33 (3)  95.22\% $\pm$ 0.13 (3)  93.69\% $\pm$ 0.21 (3)
34    87.77\% $\pm$ 0.53 (3)                     NaN                     NaN
35    87.35\% $\pm$ 0.53 (3)                     NaN                     NaN
36    87.57\% $\pm$ 0.44 (3)                     NaN                     NaN
37    88.88\% $\pm$ 0.25 (3)                     NaN                     NaN
38    89.13\% $\pm$ 0.41 (3)                     NaN                     NaN
39    91.35\% $\pm$ 0.13 (3)  95.55\% $\pm$ 0.10 (3)  95.02\% $\pm$ 0.05 (3)
40    91.97\% $\pm$ 0.21 (3)  95.02\% $\pm$ 0.13 (3)  95.13\% $\pm$ 0.32 (3)
41    92.27\% $\pm$ 0.90 (3)  95.50\% $\pm$ 1.12 (3)  95.52\% $\pm$ 0.17 (3)
42    88.41\% $\pm$ 3.11 (3)  93.99\% $\pm$ 2.46 (3)  93.66\% $\pm$ 0.14 (3)
43    91.13\% $\pm$ 0.63 (3)  95.58\% $\pm$ 0.25 (3)  95.33\% $\pm$ 0.17 (3)
44    91.19\% $\pm$ 0.67 (3)  95.64\% $\pm$ 0.05 (3)  95.30\% $\pm$ 0.10 (3)
45    91.21\% $\pm$ 0.63 (3)  95.41\% $\pm$ 0.17 (3)  95.30\% $\pm$ 0.13 (3)
46    91.44\% $\pm$ 0.77 (3)  95.13\% $\pm$ 1.13 (3)  95.83\% $\pm$ 0.08 (3)
47    91.52\% $\pm$ 0.13 (3)  94.75\% $\pm$ 1.16 (3)  93.97\% $\pm$ 0.29 (3)
48    90.91\% $\pm$ 0.38 (3)  93.22\% $\pm$ 3.15 (3)  94.88\% $\pm$ 0.13 (3)
49    90.77\% $\pm$ 1.48 (3)  93.63\% $\pm$ 3.16 (3)  94.11\% $\pm$ 0.46 (3)
50     90.99\% $\pm$ nan (1)   90.99\% $\pm$ nan (1)   95.16\% $\pm$ nan (1)
51    91.52\% $\pm$ 0.65 (3)  95.55\% $\pm$ 0.05 (3)  94.97\% $\pm$ 0.17 (3)

                     method         final_worst_acc                          \
corr                                             50                      75
0                       erm  89.36\% $\pm$ 0.55 (3)  87.95\% $\pm$ 0.63 (3)
1                   erm_dfr                     NaN  88.97\% $\pm$ 0.97 (3)
2                 erm_dfr_2  85.77\% $\pm$ 1.04 (3)  83.28\% $\pm$ 1.32 (3)
3              erm_dfr_gdro                     NaN  90.65\% $\pm$ 0.54 (3)
4            erm_dfr_gdro_2  84.79\% $\pm$ 0.89 (3)  81.68\% $\pm$ 0.74 (3)
5          erm_dfr_gdro_new                     NaN  91.48\% $\pm$ 0.59 (3)
6      erm_dfr_gdro_new_0.1                     NaN                     NaN
7     erm_dfr_gdro_new_0.25                     NaN                     NaN
8      erm_dfr_gdro_new_0.5                     NaN                     NaN
9     erm_dfr_gdro_new_0.75                     NaN                     NaN
10     erm_dfr_gdro_new_0.9                     NaN                     NaN
11              erm_dfr_new                     NaN  90.13\% $\pm$ 0.55 (3)
12           erm_dfr_rw_new                     NaN  91.12\% $\pm$ 0.47 (3)
13       erm_dfr_rw_new_0.1                     NaN                     NaN
14      erm_dfr_rw_new_0.25                     NaN                     NaN
15       erm_dfr_rw_new_0.5                     NaN                     NaN
16      erm_dfr_rw_new_0.75                     NaN                     NaN
17       erm_dfr_rw_new_0.9                     NaN                     NaN
18                 erm_gdro  86.71\% $\pm$ 0.50 (3)  85.20\% $\pm$ 0.56 (3)
19             erm_gdro_0.1                     NaN                     NaN
20            erm_gdro_0.25                     NaN                     NaN
21             erm_gdro_0.5                     NaN                     NaN
22            erm_gdro_0.75                     NaN                     NaN
23             erm_gdro_0.9                     NaN                     NaN
24            erm_gdro_frz0  90.65\% $\pm$ 0.16 (3)  90.24\% $\pm$ 0.09 (3)
25            erm_gdro_frz1  90.60\% $\pm$ 0.09 (3)  90.19\% $\pm$ 0.16 (3)
26            erm_gdro_frz2  90.65\% $\pm$ 0.16 (3)  90.24\% $\pm$ 0.36 (3)
27            erm_gdro_frz3  90.71\% $\pm$ 0.18 (3)  90.45\% $\pm$ 0.32 (3)
28            erm_gdro_frz4  90.60\% $\pm$ 0.24 (3)  90.55\% $\pm$ 0.55 (3)
29        erm_gdro_frz_rst1  90.81\% $\pm$ 0.16 (3)  90.45\% $\pm$ 0.09 (3)
30        erm_gdro_frz_rst2  90.76\% $\pm$ 0.24 (3)  90.29\% $\pm$ 0.24 (3)
31        erm_gdro_frz_rst3  90.45\% $\pm$ 0.36 (3)  89.98\% $\pm$ 0.32 (3)
32        erm_gdro_frz_rst4  90.13\% $\pm$ 0.39 (3)  90.03\% $\pm$ 0.31 (3)
33                   erm_rw  84.32\% $\pm$ 0.78 (3)  82.71\% $\pm$ 0.16 (3)
34               erm_rw_0.1                     NaN                     NaN
35              erm_rw_0.25                     NaN                     NaN
36               erm_rw_0.5                     NaN                     NaN
37              erm_rw_0.75                     NaN                     NaN
38               erm_rw_0.9                     NaN                     NaN
39                     gdro  89.56\% $\pm$ 0.16 (3)  89.72\% $\pm$ 0.41 (3)
40                   gdro_1  90.86\% $\pm$ 0.18 (3)  90.45\% $\pm$ 0.09 (3)
41                 gdro_dfr                     NaN  89.52\% $\pm$ 1.06 (3)
42                 gdro_erm  87.95\% $\pm$ 0.48 (3)  87.28\% $\pm$ 2.03 (3)
43            gdro_erm_frz1  88.32\% $\pm$ 0.00 (3)  87.33\% $\pm$ 0.09 (3)
44            gdro_erm_frz2  88.11\% $\pm$ 0.09 (3)  87.28\% $\pm$ 0.09 (3)
45            gdro_erm_frz3  88.47\% $\pm$ 0.27 (3)  87.69\% $\pm$ 0.27 (3)
46            gdro_erm_frz4  88.58\% $\pm$ 0.45 (3)  88.16\% $\pm$ 0.97 (3)
47                gdro_gdro  90.29\% $\pm$ 0.70 (3)  89.51\% $\pm$ 1.18 (3)
48              gdro_gdro_1  90.71\% $\pm$ 0.24 (3)  90.19\% $\pm$ 0.54 (3)
49            gdro_gdro_dfr                     NaN  91.14\% $\pm$ 0.96 (3)
50                  gdro_rw   91.12\% $\pm$ nan (1)   89.72\% $\pm$ nan (1)
51                   rw_erm  89.62\% $\pm$ 0.24 (3)  89.77\% $\pm$ 0.63 (3)


corr                      95                     625                     875
0     72.95\% $\pm$ 0.36 (3)  89.72\% $\pm$ 0.41 (3)  81.62\% $\pm$ 0.87 (3)
1     80.84\% $\pm$ 1.35 (3)  88.58\% $\pm$ 0.50 (3)  85.51\% $\pm$ 1.95 (3)
2     71.35\% $\pm$ 5.96 (3)  86.76\% $\pm$ 0.82 (3)  78.30\% $\pm$ 3.33 (3)
3     85.36\% $\pm$ 0.81 (3)  91.43\% $\pm$ 0.44 (2)  89.10\% $\pm$ 0.82 (3)
4     69.07\% $\pm$ 6.49 (3)  86.19\% $\pm$ 0.70 (3)  76.43\% $\pm$ 4.37 (3)
5     88.99\% $\pm$ 0.65 (3)  91.43\% $\pm$ 0.41 (3)  90.86\% $\pm$ 0.74 (3)
6     81.15\% $\pm$ 7.18 (3)                     NaN                     NaN
7     85.49\% $\pm$ 2.22 (3)                     NaN                     NaN
8     87.27\% $\pm$ 0.72 (3)                     NaN                     NaN
9     88.72\% $\pm$ 1.15 (3)                     NaN                     NaN
10    89.75\% $\pm$ 0.05 (3)                     NaN                     NaN
11    87.69\% $\pm$ 1.09 (3)  90.76\% $\pm$ 0.09 (3)  89.56\% $\pm$ 0.78 (3)
12    88.89\% $\pm$ 0.78 (3)  91.07\% $\pm$ 0.24 (3)  90.91\% $\pm$ 0.80 (3)
13    81.15\% $\pm$ 7.18 (3)                     NaN                     NaN
14    85.15\% $\pm$ 1.82 (3)                     NaN                     NaN
15    86.89\% $\pm$ 0.45 (3)                     NaN                     NaN
16    88.36\% $\pm$ 1.12 (3)                     NaN                     NaN
17    89.57\% $\pm$ 0.19 (3)                     NaN                     NaN
18    73.78\% $\pm$ 2.92 (3)  87.28\% $\pm$ 0.18 (3)  79.08\% $\pm$ 1.60 (3)
19    53.95\% $\pm$ 2.74 (3)                     NaN                     NaN
20    62.41\% $\pm$ 3.33 (3)                     NaN                     NaN
21    67.74\% $\pm$ 0.68 (3)                     NaN                     NaN
22    73.26\% $\pm$ 3.30 (3)                     NaN                     NaN
23    72.33\% $\pm$ 1.15 (3)                     NaN                     NaN
24    83.80\% $\pm$ 0.62 (3)  91.69\% $\pm$ 0.36 (3)  89.10\% $\pm$ 0.82 (3)
25    83.74\% $\pm$ 0.85 (3)  91.64\% $\pm$ 0.32 (3)  88.89\% $\pm$ 0.99 (3)
26    83.90\% $\pm$ 0.59 (3)  91.80\% $\pm$ 0.09 (3)  89.15\% $\pm$ 0.63 (3)
27    84.48\% $\pm$ 0.80 (3)  91.80\% $\pm$ 0.18 (3)  89.25\% $\pm$ 0.62 (3)
28    84.90\% $\pm$ 0.02 (3)  92.06\% $\pm$ 0.27 (3)  89.04\% $\pm$ 0.24 (3)
29    87.28\% $\pm$ 0.18 (3)  91.59\% $\pm$ 0.16 (3)  89.24\% $\pm$ 0.02 (3)
30    86.65\% $\pm$ 0.08 (3)  91.59\% $\pm$ 0.16 (3)  89.01\% $\pm$ 0.08 (3)
31    85.49\% $\pm$ 0.34 (3)  91.64\% $\pm$ 0.32 (3)  88.53\% $\pm$ 0.09 (3)
32    84.56\% $\pm$ 0.52 (3)  92.06\% $\pm$ 0.27 (3)  88.99\% $\pm$ 0.18 (3)
33    66.20\% $\pm$ 2.16 (3)  86.55\% $\pm$ 0.50 (3)  75.34\% $\pm$ 1.15 (3)
34    49.43\% $\pm$ 1.04 (3)                     NaN                     NaN
35    56.28\% $\pm$ 2.16 (3)                     NaN                     NaN
36    63.29\% $\pm$ 3.33 (3)                     NaN                     NaN
37    66.46\% $\pm$ 2.21 (3)                     NaN                     NaN
38    66.25\% $\pm$ 0.80 (3)                     NaN                     NaN
39    86.14\% $\pm$ 0.88 (3)  91.04\% $\pm$ 0.23 (3)  88.75\% $\pm$ 1.11 (3)
40    87.31\% $\pm$ 0.27 (3)  91.69\% $\pm$ 0.09 (3)  89.30\% $\pm$ 0.09 (3)
41    75.34\% $\pm$ 0.70 (3)  88.11\% $\pm$ 2.66 (3)  88.84\% $\pm$ 0.30 (3)
42    66.61\% $\pm$ 2.96 (3)  87.51\% $\pm$ 3.85 (3)  87.73\% $\pm$ 0.21 (3)
43    73.10\% $\pm$ 2.18 (3)  91.11\% $\pm$ 0.54 (3)  84.89\% $\pm$ 0.41 (3)
44    73.16\% $\pm$ 1.56 (3)  91.07\% $\pm$ 0.24 (3)  84.89\% $\pm$ 0.41 (3)
45    73.00\% $\pm$ 1.00 (3)  91.17\% $\pm$ 0.18 (3)  84.79\% $\pm$ 0.59 (3)
46    71.60\% $\pm$ 1.31 (3)  90.33\% $\pm$ 0.96 (3)  84.84\% $\pm$ 0.32 (3)
47    87.08\% $\pm$ 0.29 (3)  90.19\% $\pm$ 0.82 (3)  89.15\% $\pm$ 0.32 (3)
48    87.46\% $\pm$ 0.22 (3)  90.44\% $\pm$ 2.40 (3)  88.89\% $\pm$ 0.32 (3)
49    83.33\% $\pm$ 1.33 (3)  89.08\% $\pm$ 3.15 (3)  90.17\% $\pm$ 0.42 (3)
50     87.18\% $\pm$ nan (1)   87.32\% $\pm$ nan (1)   88.47\% $\pm$ nan (1)
51    86.31\% $\pm$ 0.30 (3)  90.91\% $\pm$ 0.50 (3)  88.06\% $\pm$ 1.64 (3)

                     method           final_avg_acc                          \
corr                                             50                      75
0                       erm  96.20\% $\pm$ 0.12 (3)  95.50\% $\pm$ 0.06 (3)
1                   erm_dfr                     NaN  95.73\% $\pm$ 0.11 (3)
2                 erm_dfr_2  96.06\% $\pm$ 0.11 (3)  95.21\% $\pm$ 0.21 (3)
3              erm_dfr_gdro                     NaN  95.33\% $\pm$ 0.30 (3)
4            erm_dfr_gdro_2  96.00\% $\pm$ 0.10 (3)  95.13\% $\pm$ 0.19 (3)
5          erm_dfr_gdro_new                     NaN  95.24\% $\pm$ 0.21 (3)
6      erm_dfr_gdro_new_0.1                     NaN                     NaN
7     erm_dfr_gdro_new_0.25                     NaN                     NaN
8      erm_dfr_gdro_new_0.5                     NaN                     NaN
9     erm_dfr_gdro_new_0.75                     NaN                     NaN
10     erm_dfr_gdro_new_0.9                     NaN                     NaN
11              erm_dfr_new                     NaN  95.25\% $\pm$ 0.19 (3)
12           erm_dfr_rw_new                     NaN  95.28\% $\pm$ 0.25 (3)
13       erm_dfr_rw_new_0.1                     NaN                     NaN
14      erm_dfr_rw_new_0.25                     NaN                     NaN
15       erm_dfr_rw_new_0.5                     NaN                     NaN
16      erm_dfr_rw_new_0.75                     NaN                     NaN
17       erm_dfr_rw_new_0.9                     NaN                     NaN
18                 erm_gdro  96.01\% $\pm$ 0.06 (3)  95.37\% $\pm$ 0.06 (3)
19             erm_gdro_0.1                     NaN                     NaN
20            erm_gdro_0.25                     NaN                     NaN
21             erm_gdro_0.5                     NaN                     NaN
22            erm_gdro_0.75                     NaN                     NaN
23             erm_gdro_0.9                     NaN                     NaN
24            erm_gdro_frz0  96.16\% $\pm$ 0.10 (3)  95.70\% $\pm$ 0.06 (3)
25            erm_gdro_frz1  96.17\% $\pm$ 0.08 (3)  95.74\% $\pm$ 0.05 (3)
26            erm_gdro_frz2  96.17\% $\pm$ 0.06 (3)  95.73\% $\pm$ 0.06 (3)
27            erm_gdro_frz3  96.18\% $\pm$ 0.05 (3)  95.70\% $\pm$ 0.08 (3)
28            erm_gdro_frz4  96.17\% $\pm$ 0.13 (3)  95.69\% $\pm$ 0.05 (3)
29        erm_gdro_frz_rst1  95.61\% $\pm$ 0.11 (3)  95.27\% $\pm$ 0.08 (3)
30        erm_gdro_frz_rst2  95.70\% $\pm$ 0.07 (3)  95.21\% $\pm$ 0.07 (3)
31        erm_gdro_frz_rst3  95.88\% $\pm$ 0.07 (3)  95.41\% $\pm$ 0.10 (3)
32        erm_gdro_frz_rst4  96.17\% $\pm$ 0.11 (3)  95.60\% $\pm$ 0.05 (3)
33                   erm_rw  95.94\% $\pm$ 0.06 (3)  95.25\% $\pm$ 0.10 (3)
34               erm_rw_0.1                     NaN                     NaN
35              erm_rw_0.25                     NaN                     NaN
36               erm_rw_0.5                     NaN                     NaN
37              erm_rw_0.75                     NaN                     NaN
38               erm_rw_0.9                     NaN                     NaN
39                     gdro  96.36\% $\pm$ 0.14 (3)  95.78\% $\pm$ 0.04 (3)
40                   gdro_1  95.62\% $\pm$ 0.10 (3)  95.24\% $\pm$ 0.02 (3)
41                 gdro_dfr                     NaN  95.26\% $\pm$ 0.11 (3)
42                 gdro_erm  95.79\% $\pm$ 0.09 (3)  94.76\% $\pm$ 0.11 (3)
43            gdro_erm_frz1  96.21\% $\pm$ 0.05 (3)  95.60\% $\pm$ 0.12 (3)
44            gdro_erm_frz2  96.20\% $\pm$ 0.05 (3)  95.59\% $\pm$ 0.11 (3)
45            gdro_erm_frz3  96.24\% $\pm$ 0.08 (3)  95.63\% $\pm$ 0.10 (3)
46            gdro_erm_frz4  96.31\% $\pm$ 0.05 (3)  95.86\% $\pm$ 0.09 (3)
47                gdro_gdro  94.51\% $\pm$ 0.66 (3)  94.97\% $\pm$ 0.80 (3)
48              gdro_gdro_1  95.25\% $\pm$ 0.29 (3)  94.96\% $\pm$ 0.27 (3)
49            gdro_gdro_dfr                     NaN  93.97\% $\pm$ 0.25 (3)
50                  gdro_rw   95.69\% $\pm$ nan (1)   95.15\% $\pm$ nan (1)
51                   rw_erm  96.39\% $\pm$ 0.14 (3)  95.80\% $\pm$ 0.10 (3)


corr                      95                     625                     875
0     88.49\% $\pm$ 0.14 (3)  96.17\% $\pm$ 0.12 (3)  93.72\% $\pm$ 0.21 (3)
1     94.01\% $\pm$ 0.15 (3)  95.77\% $\pm$ 0.28 (3)  95.26\% $\pm$ 0.04 (3)
2     90.32\% $\pm$ 0.22 (3)  95.92\% $\pm$ 0.25 (3)  94.03\% $\pm$ 0.07 (3)
3     93.27\% $\pm$ 0.25 (3)  95.79\% $\pm$ 0.12 (2)  94.57\% $\pm$ 0.11 (3)
4     90.20\% $\pm$ 0.31 (3)  95.88\% $\pm$ 0.22 (3)  94.00\% $\pm$ 0.01 (3)
5     93.27\% $\pm$ 0.26 (3)  95.39\% $\pm$ 0.29 (3)  94.85\% $\pm$ 0.43 (3)
6     88.93\% $\pm$ 4.30 (3)                     NaN                     NaN
7     91.16\% $\pm$ 1.59 (3)                     NaN                     NaN
8     92.16\% $\pm$ 0.76 (3)                     NaN                     NaN
9     93.00\% $\pm$ 0.46 (3)                     NaN                     NaN
10    93.25\% $\pm$ 0.47 (3)                     NaN                     NaN
11    92.80\% $\pm$ 0.63 (3)  95.47\% $\pm$ 0.23 (3)  94.82\% $\pm$ 0.39 (3)
12    93.25\% $\pm$ 0.22 (3)  95.43\% $\pm$ 0.27 (3)  94.97\% $\pm$ 0.30 (3)
13    88.83\% $\pm$ 4.47 (3)                     NaN                     NaN
14    91.19\% $\pm$ 1.73 (3)                     NaN                     NaN
15    92.12\% $\pm$ 0.74 (3)                     NaN                     NaN
16    92.99\% $\pm$ 0.36 (3)                     NaN                     NaN
17    93.27\% $\pm$ 0.37 (3)                     NaN                     NaN
18    92.11\% $\pm$ 0.15 (3)  95.97\% $\pm$ 0.11 (3)  94.59\% $\pm$ 0.13 (3)
19    89.01\% $\pm$ 0.36 (3)                     NaN                     NaN
20    88.68\% $\pm$ 0.36 (3)                     NaN                     NaN
21    88.72\% $\pm$ 0.19 (3)                     NaN                     NaN
22    91.22\% $\pm$ 0.18 (3)                     NaN                     NaN
23    91.54\% $\pm$ 0.42 (3)                     NaN                     NaN
24    92.08\% $\pm$ 0.37 (3)  96.17\% $\pm$ 0.06 (3)  95.38\% $\pm$ 0.12 (3)
25    92.10\% $\pm$ 0.42 (3)  96.17\% $\pm$ 0.06 (3)  95.40\% $\pm$ 0.15 (3)
26    92.20\% $\pm$ 0.32 (3)  96.20\% $\pm$ 0.09 (3)  95.35\% $\pm$ 0.10 (3)
27    92.13\% $\pm$ 0.40 (3)  96.17\% $\pm$ 0.06 (3)  95.29\% $\pm$ 0.07 (3)
28    92.52\% $\pm$ 0.24 (3)  96.05\% $\pm$ 0.12 (3)  95.27\% $\pm$ 0.08 (3)
29    92.98\% $\pm$ 0.10 (3)  95.79\% $\pm$ 0.08 (3)  94.75\% $\pm$ 0.09 (3)
30    92.77\% $\pm$ 0.06 (3)  95.88\% $\pm$ 0.04 (3)  94.75\% $\pm$ 0.12 (3)
31    92.72\% $\pm$ 0.14 (3)  96.02\% $\pm$ 0.06 (3)  94.93\% $\pm$ 0.13 (3)
32    92.18\% $\pm$ 0.32 (3)  95.99\% $\pm$ 0.11 (3)  95.04\% $\pm$ 0.15 (3)
33    90.25\% $\pm$ 0.26 (3)  95.95\% $\pm$ 0.10 (3)  93.99\% $\pm$ 0.22 (3)
34    88.99\% $\pm$ 0.34 (3)                     NaN                     NaN
35    88.71\% $\pm$ 0.39 (3)                     NaN                     NaN
36    88.65\% $\pm$ 0.23 (3)                     NaN                     NaN
37    89.86\% $\pm$ 0.33 (3)                     NaN                     NaN
38    90.17\% $\pm$ 0.34 (3)                     NaN                     NaN
39    91.87\% $\pm$ 0.38 (3)  96.38\% $\pm$ 0.05 (3)  94.72\% $\pm$ 0.03 (3)
40    92.87\% $\pm$ 0.08 (3)  95.69\% $\pm$ 0.09 (3)  94.75\% $\pm$ 0.08 (3)
41    92.24\% $\pm$ 0.55 (3)  94.24\% $\pm$ 1.95 (3)  94.82\% $\pm$ 0.31 (3)
42    88.94\% $\pm$ 2.99 (3)  93.83\% $\pm$ 2.80 (3)  93.34\% $\pm$ 0.11 (3)
43    91.76\% $\pm$ 0.95 (3)  96.14\% $\pm$ 0.36 (3)  94.65\% $\pm$ 0.08 (3)
44    91.78\% $\pm$ 0.94 (3)  96.17\% $\pm$ 0.33 (3)  94.67\% $\pm$ 0.10 (3)
45    91.80\% $\pm$ 0.94 (3)  96.13\% $\pm$ 0.39 (3)  94.72\% $\pm$ 0.11 (3)
46    92.00\% $\pm$ 0.97 (3)  95.79\% $\pm$ 1.32 (3)  95.10\% $\pm$ 0.07 (3)
47    92.16\% $\pm$ 0.28 (3)  95.56\% $\pm$ 1.33 (3)  93.23\% $\pm$ 0.03 (3)
48    91.58\% $\pm$ 0.63 (3)  93.64\% $\pm$ 3.07 (3)  94.69\% $\pm$ 0.04 (3)
49    90.61\% $\pm$ 0.88 (3)  91.65\% $\pm$ 4.40 (3)  92.84\% $\pm$ 0.54 (3)
50     91.68\% $\pm$ nan (1)   91.65\% $\pm$ nan (1)   94.75\% $\pm$ nan (1)
51    92.11\% $\pm$ 0.40 (3)  96.35\% $\pm$ 0.08 (3)  94.74\% $\pm$ 0.03 (3)

In [16]:
dataset = "CelebA"
results = dict()
splits = ['val','test']
for s in splits:
    results[s] =create_results_table(dataset, s)
    display(create_final_table(results[s]['means'],"worst_acc"))
    display(create_final_table(results[s]['means'],"avg_acc"))

        method         final_worst_acc
corr                               0.9
0         gdro  91.23\% $\pm$ 0.55 (3)
1     jtt_1_50  47.15\% $\pm$ 2.21 (3)

        method           final_avg_acc
corr                               0.9
0         gdro  93.67\% $\pm$ 0.15 (3)
1     jtt_1_50  81.98\% $\pm$ 0.71 (3)

        method         final_worst_acc
corr                               0.9
0         gdro  91.05\% $\pm$ 0.47 (3)
1     jtt_1_50  48.78\% $\pm$ 1.60 (3)

        method           final_avg_acc
corr                               0.9
0         gdro  93.95\% $\pm$ 0.07 (3)
1     jtt_1_50  83.19\% $\pm$ 0.67 (3)

In [6]:
df = results['test']['means']
if dataset =="CUB":
    df['corr'] = df['corr'].apply(lambda x: a[x])
methods = ['erm',"rw","erm_rw"
            ,'erm_rw_0.1'
          ,'erm_rw_0.25'
          ,'erm_rw_0.5'
          ,'erm_rw_0.75'
          ,'erm_rw_0.9',
           'gdro'
           ,'erm_gdro_frz0'
           ,'erm_gdro_frz1'
           ,'erm_gdro_frz2'
           ,'erm_gdro_frz3'
           ,'erm_gdro_frz4'
                      ,'erm_gdro_0.1'
                      ,'erm_gdro_0.25'
                      ,'erm_gdro_0.5'
                      ,'erm_gdro_0.75'
                      ,'erm_gdro_0.9'
           ,'erm_gdro_frz_rst1'
           ,'erm_gdro_frz_rst2'
           ,'erm_gdro_frz_rst3'
           ,'erm_gdro_frz_rst4',
           "erm_gdro",
          "gdro_erm",
          'gdro_erm_frz1',
          'gdro_erm_frz2',
          'gdro_erm_frz3',
          'gdro_erm_frz4',
          "erm_dfr_new",
          "erm_dfr_rw_new",
           "erm_dfr",
           "erm_dfr_gdro",
           "erm_dfr_rw",
          "gdro_gdro_1",
          "gdro_gdro_dfr",
          "erm_dfr_gdro_new",
          "erm_dfr_gdro_0.1",
           "erm_dfr_gdro_0.25",
           "erm_dfr_gdro_0.5"
          ]
orden = {'erm' : 0
         ,"rw": 0.1
        ,"erm_rw": 0.2
         ,'erm_rw_0.1': 0.21
          ,'erm_rw_0.25': 0.22
          ,'erm_rw_0.5': 0.23
          ,'erm_rw_0.75': 0.24
          ,'erm_rw_0.9': 0.25
            ,'gdro': 1
           ,'erm_gdro_frz0': 3
           ,'erm_gdro_frz1': 4
           ,'erm_gdro_frz2': 5
           ,'erm_gdro_frz3': 6
           ,'erm_gdro_frz4': 7
           ,'erm_gdro_frz_rst1': 9
           ,'erm_gdro_frz_rst2': 10
           ,'erm_gdro_frz_rst3': 11
           ,'erm_gdro_frz_rst4': 12
           ,"erm_gdro": 2
            ,'erm_gdro_0.1': 2.1
            ,'erm_gdro_0.25': 2.2
            ,'erm_gdro_0.5': 2.3
            ,'erm_gdro_0.75': 2.4
            ,'erm_gdro_0.9': 2.5
          , "gdro_erm": 13
          ,'gdro_erm_frz1': 14
          ,'gdro_erm_frz2': 15
          ,'gdro_erm_frz3': 16
          ,'gdro_erm_frz4': 17
          , "gdro_gdro_1": 20
          , "erm_dfr_new": 18
          , "erm_dfr_rw_new": 18.2
          , "erm_dfr_gdro_new": 18.5,
           "erm_dfr": 18
          , "erm_dfr_rw": 18.2
          , "erm_dfr_gdro": 18.5,
            "erm_dfr_gdro_0.1": 18.6,
           "erm_dfr_gdro_0.25": 18.7,
           "erm_dfr_gdro_0.5": 18.8
          ,"gdro_gdro_dfr": 19}
methods_to_name = {'erm' : "ERM",
                   "rw": "RW",
                   "erm_rw": "ERM + RW"
                    ,'erm_rw_0.1': "ERM + RW (10%)"
                  ,'erm_rw_0.25': "ERM + RW (25%)"
                  ,'erm_rw_0.5': "ERM + RW (50%)"
                  ,'erm_rw_0.75': "ERM + RW (75%)"
                  ,'erm_rw_0.9': "ERM + RW (90%)"
                   ,'gdro': "GDRO"
            ,'erm_gdro_0.1': "ERM + GDRO (10%)"
            ,'erm_gdro_0.25':"ERM + GDRO (25%)"
            ,'erm_gdro_0.5': "ERM + GDRO (50%)"
            ,'erm_gdro_0.75': "ERM + GDRO (75%)"
            ,'erm_gdro_0.9': "ERM + GDRO (90%)"
           ,'erm_gdro_frz0': "ERM + GDRO (UNFROZEN)"
           ,'erm_gdro_frz1': "ERM + GDRO (FRZ1)"
           ,'erm_gdro_frz2': "ERM + GDRO (FRZ2)"
           ,'erm_gdro_frz3': "ERM + GDRO (FRZ3)"
           ,'erm_gdro_frz4': "ERM + GDRO (FRZ4)"
           ,'erm_gdro_frz_rst1': "ERM + GDRO (RST1)"
           ,'erm_gdro_frz_rst2': "ERM + GDRO (RST2)"
           ,'erm_gdro_frz_rst3': "ERM + GDRO (RST3)"
           ,'erm_gdro_frz_rst4': "ERM + GDRO (RST4)"
           ,"erm_gdro": "ERM + GDRO + CLS"
          , "gdro_erm": "GDRO + ERM"
          ,'gdro_erm_frz1': "GDRO + ERM (FRZ1)"
          ,'gdro_erm_frz2': "GDRO + ERM (FRZ2)"
          ,'gdro_erm_frz3': "GDRO + ERM (FRZ3)"
          ,'gdro_erm_frz4': "GDRO + ERM (FRZ4)"
          , "gdro_gdro_1": "GDRO + GDRO"
          , "erm_dfr_new": "SUBG"
          , "erm_dfr_rw_new": "GDRFR (RW)"
          , "erm_dfr_gdro_new": "GDRFR (GDRO)"
          , "erm_dfr": "SUBG"
          , "erm_dfr_rw": "GDRFR (RW)"
          , "erm_dfr_gdro": "GDRFR (GDRO)"     
           , "erm_dfr_gdro_0.1": "ERM + DFR (GDRO) 10%",
           "erm_dfr_gdro_0.25": "ERM + DFR (GDRO) 25%",
           "erm_dfr_gdro_0.5": "ERM + DFR (GDRO) 50%"
          ,"gdro_gdro_dfr": "GDRO + DFR (GDRO)"}

df = df[df['method'].isin(methods)]
final_table = create_final_table(df,"worst_acc")
final_table['order'] = final_table['method'].map(orden)
final_table['method'] = final_table['method'].apply(lambda x: methods_to_name[x])
final_table = final_table.sort_values(by="order")
# Dropping the 'order' column and setting 'method' as index
final_table = final_table.drop(columns='order')
final_table.set_index("method")
print(final_table.to_latex(index=False,escape=False))

\begin{tabular}{llllll}
\toprule
          method & \multicolumn{5}{l}{final_worst_acc} \\
                 &                    0.0 &                   0.25 &                    0.5 &                   0.75 &                    0.9 \\
\midrule
             ERM & 88.62\% $\pm$ 0.93 (3) & 82.38\% $\pm$ 0.62 (3) & 78.21\% $\pm$ 0.89 (3) & 55.23\% $\pm$ 5.18 (3) & 30.17\% $\pm$ 2.99 (3) \\
        ERM + RW & 89.16\% $\pm$ 1.20 (3) & 88.08\% $\pm$ 1.02 (3) & 89.93\% $\pm$ 0.28 (3) & 85.85\% $\pm$ 0.77 (3) & 82.74\% $\pm$ 0.46 (3) \\
  ERM + RW (10%) &                    NaN &                    NaN &                    NaN &                    NaN & 81.03\% $\pm$ 1.81 (3) \\
  ERM + RW (25%) &                    NaN &                    NaN &                    NaN &                    NaN & 81.94\% $\pm$ 1.03 (3) \\
  ERM + RW (50%) &                    NaN &                    NaN &                    NaN &                    NaN & 82.03\% $\pm$ 0.20 (3) \\
  ERM + RW (75%) &                    NaN &                    NaN &                    NaN &                    NaN & 82.21\% $\pm$ 0.00 (3) \\
  ERM + RW (90%) &                    NaN &                    NaN &                    NaN &                    NaN & 82.74\% $\pm$ 0.46 (3) \\
            GDRO & 88.09\% $\pm$ 1.23 (3) & 88.21\% $\pm$ 1.08 (3) & 88.99\% $\pm$ 0.95 (3) & 85.49\% $\pm$ 0.93 (3) & 85.24\% $\pm$ 1.14 (3) \\
ERM + GDRO + CLS & 88.76\% $\pm$ 1.06 (3) & 87.94\% $\pm$ 1.02 (3) & 89.38\% $\pm$ 0.77 (3) & 86.10\% $\pm$ 0.93 (3) & 82.74\% $\pm$ 0.99 (3) \\
ERM + GDRO (10%) &                    NaN &                    NaN &                    NaN &                    NaN & 80.84\% $\pm$ 2.23 (3) \\
ERM + GDRO (25%) &                    NaN &                    NaN &                    NaN &                    NaN & 82.08\% $\pm$ 1.21 (3) \\
ERM + GDRO (50%) &                    NaN &                    NaN &                    NaN &                    NaN & 82.48\% $\pm$ 0.23 (3) \\
ERM + GDRO (75%) &                    NaN &                    NaN &                    NaN &                    NaN & 82.35\% $\pm$ 0.60 (3) \\
ERM + GDRO (90%) &                    NaN &                    NaN &                    NaN &                    NaN & 82.43\% $\pm$ 0.85 (3) \\
            SUBG &                    NaN & 88.76\% $\pm$ 0.00 (3) & 87.82\% $\pm$ 0.46 (3) & 86.48\% $\pm$ 0.46 (3) & 82.48\% $\pm$ 1.28 (3) \\
      GDRFR (RW) &                    NaN & 89.02\% $\pm$ 0.23 (3) & 88.62\% $\pm$ 0.23 (3) & 86.61\% $\pm$ 0.23 (3) & 82.46\% $\pm$ 1.62 (3) \\
    GDRFR (GDRO) &                    NaN & 88.76\% $\pm$ 0.40 (3) & 88.22\% $\pm$ 0.46 (3) & 86.61\% $\pm$ 0.61 (3) & 82.74\% $\pm$ 1.06 (3) \\
\bottomrule
\end{tabular}

In [ ]:
a = {50: 0.0, 625: 0.25, 75: 0.5, 875: 0.75, 95: 0.9}

In [ ]:
import matplotlib.pyplot as plt
corrs  = [0.0, 0.25, 0.5, 0.75, 0.9, 1.0]

data = [v['epoch'] for v in results.values()]
#data = [train_rs_v[-1],val_rs_v[-1],test_rs_v[-1]]
def plot_methods(ax, df, corr, methods = ["erm"], split="train", metric="avg_acc"):
    data = df[df['corr'] == corr]
  #  fig, ax = plt.subplots(nrows=1,ncols=1)
    for m in methods:
        d = data[data['method']==m]
        x = d['epoch']
        y = d[metric]
        ax.plot(x,y,label=m)
    ax.legend()    
    ax.set_title(f"{split.capitalize()} Accuracy vs Epochs - Corr: {corr}")
    return ax

fig, axs = plt.subplots(nrows=len(corrs), ncols=len(splits), figsize=(len(corrs)*4,30),sharey="row")
for i, corr in enumerate(corrs):
    for j, split in enumerate(splits):
        axs[i,j] = plot_methods(axs[i,j],
                          data[j],
                          corr,
                          methods=["erm","gdro","reweight"],
                          split=split,
                        metric = "avg_acc")
fig.show()

In [ ]:
fig, axs = plt.subplots(nrows=len(corrs), ncols=len(splits), figsize=(len(corrs)*4,30),sharey="row")
for i, corr in enumerate(corrs):
    for j, split in enumerate(splits):
        axs[i,j] = plot_methods(axs[i,j],
                          data[j],
                          corr,
                          methods=["erm","gdro","reweight"],
                          split=split,
                        metric = "worst_acc")
fig.show()

In [ ]:
exps = [join(f.path ,"model_outputs")  for f in scandir(dataset) if "svdrop" in f.path]

In [ ]:
v = results['val']['all']
v[(v['corr'] == 1.0) & (v['epoch'] == 2000)][
    ['method',
     'avg_acc_group:0',
     'processed_data_count_group:0',
     'avg_acc_group:1',
     'processed_data_count_group:1',
     'avg_acc_group:2',
     'processed_data_count_group:2',
     'avg_acc_group:3',
     'processed_data_count_group:3',
     'avg_acc']]

In [ ]:
v

In [ ]:
results['val']['seed'][results['val']['seed']['corr']==1.0]

In [ ]:
grouped_df.groupby(['method','corr']).mean().reset_index()

In [ ]:
df = pd.read_csv("MNISTCIFAR_val.csv")
df['worst_acc'] = df[['avg_acc_group:0','avg_acc_group:1','avg_acc_group:2','avg_acc_group:3']].min(axis=1)

In [ ]:
grouped_df = df.groupby(['method','corr',"seed"])['worst_acc'].max().reset_index()

In [ ]:
df = pd.read_csv("MNISTCIFAR_val.csv")

In [ ]:
df

In [ ]:
df.loc[df.index > 432215].to_csv('MNISTCIFAR_test.csv')

In [7]:
import shutil

models = []
dataset = "CUB"
for f in scandir(dataset):
    for f1 in scandir(f.path):
        models.append(join(f1.path,f"best_model.pth"))
results  = pd.DataFrame()
# Create 
for f in models:
    data = f.split("/")[1]
    method = "_".join(data.split("_")[:-1])
    corr = data.split("_")[-1]
    seed = f.split("/")[2].split("_")[-1]
    output_file_name = f"../pretrained_models/{dataset}/{method}_{corr}_{seed}.pth"
    shutil.copy(f,output_file_name)

In [ ]:
!ls ../pretrained_models/CUB

In [ ]:
import os
models = []
dataset = "MNISTCIFAR"
for f in scandir(dataset):
    for f1 in scandir(f.path):
        for f2 in scandir(f1.path):
            if ".pth" in f2.path:
                filename = f2.path.split("/")[-1]
                name =  filename#.split(".")#[0]
                names = [f"{i*100}_model.pth" for i in range(0,500)]
                names.append("best_model.pth")
                if name not in names:#["0_model","10_model","25_model","50_model","100_model","150_model","200_model","300_model","best_model"]: 
                    # remove f2 if not best_model.pth
                    print(f"Removing: {name} {f2.path}")
                    os.remove(f2.path)

In [ ]:
import os
models = []
dataset = "MNISTCIFAR"
names = [f"output_train_epoch_{i*1000}.csv" for i in range(0,6)]
names += [f"output_val_epoch_{i*1000}.csv" for i in range(0,6)]
names += [f"output_test_epoch_{i*1000}.csv" for i in range(0,6)]
names.append("train.csv")
names.append("val.csv")
names.append("test.csv")
for f in scandir(dataset):
    for f1 in scandir(f.path):
        for f2 in scandir(f1.path):
            if ".csv" in f2.path:
                filename = f2.path.split("/")[-1]
                name =  filename#.split(".")#[0]
                if name not in names:#["0_model","10_model","25_model","50_model","100_model","150_model","200_model","300_model","best_model"]: 
                    # remove f2 if not best_model.pth
                    print(f"Removing: {name} {f2.path}")
                    os.remove(f2.path)

In [17]:
from torchvision.models import resnet50
m = resnet50()
m1 = resnet50()

In [18]:
m_sd = m.state_dict()
m1_sd = m1.state_dict()

In [19]:
print(m_sd['layer1.0.conv3.weight'][0][0],
m1_sd['layer1.0.conv3.weight'][0][0])

tensor([[-0.0096]]) tensor([[-0.0561]])

In [23]:

def update_state_dict(old, new, layers=["layer4"]):
    # old and new must have same keys
    keys1 = set(old.keys())
    keys2 = set(old.keys())
    assert keys1 == keys2, "Dictionaries do not have the same keys"
    results = {k:v for k,v in old.items()}
    for k, v in new.items():
        for layer in layers:
            if layer in k:
                results[k] = v # update with new value
    return results

r = update_state_dict(m_sd, m1_sd, layers=['layer1',"layer2"])
print(m_sd['layer1.0.conv3.weight'][0][0],
m1_sd['layer1.0.conv3.weight'][0][0],
     r['layer1.0.conv3.weight'][0][0],
     m_sd['layer2.0.conv3.weight'][0][0],
m1_sd['layer2.0.conv3.weight'][0][0],
     r['layer2.0.conv3.weight'][0][0])

tensor([[-0.0096]]) tensor([[-0.0561]]) tensor([[-0.0561]]) tensor([[0.1081]]) tensor([[0.0353]]) tensor([[0.0353]])